(function(){function B(a,c,b){if(a.length==c)return b;a=a.substr(c);return/^[0-9]+$/.exec(a)?b+"["+a+"]":b+"."+a}function t(a,c,b){var d,e=M.exec(a);e?(d=[e[1]],a=e[2],c=Array(1)):(e=N.exec(a))?(d=e[1].split(/\s*,\s*/),a=e[2],c=Array(d.length)):c=Array(c);for(var e=0,h=c.length;e<h;++e)c[e]=0;var h=0,g="";if(d)for(;e=F.exec(a);)for(var p=e[0],l=0,m=d.length;l<m;++l){if(p==d[l]){++c[l];b&&(b.push(a.substring(h,e.index)),b.push(l),h=e.index+p.length);break}}else for(d="";e=F.exec(a);)p=e[0],m=p.charAt(0),
l=null,"$"==m?(m=p.length,2<=m&&"$"==p[1]?(++c[1],b&&(l=1,d=B(p,2,""))):(++c[0],b&&(l=0,d=B(p,1,"")))):"@"==m?(m=c.length-1,++c[m],b&&(l=m,d=B(p,1,""))):"#"==m&&(m=parseInt(p.substr(1)),++c[m],b&&(l=m,d="")),b&&null!==l&&(b.push(g+a.substring(h,e.index)),b.push(l),h=e.index+p.length,g=d,d="");b&&b.push(g+a.substring(h,a.length));return c}function k(a,c,b){var d,e=M.exec(a);if(e)d=[e[1]],a=e[2];else if(e=N.exec(a))d=e[1].split(/\s*,\s*/),a=e[2];var h=arguments,g=0<h.length?h[h.length-1]:"";return d?
a.replace(F,function(a){for(var b=0,c=d.length;b<c;++b)if(a==d[b])return h[b+1];return a}):a.replace(F,function(a){var d=a.charAt(0);return"$"==d?2<=a.length&&"$"==a[1]?B(a,2,b):B(a,1,c):"@"==d?B(a,1,g):"#"==d?h[parseInt(a.substr(1))+1]:a})}function s(a,c,b){for(var d=1,e=a.length;d<e;d+=2){var h=a[d];"number"==typeof h&&(a[d]=arguments[h+1])}return a.join("")}function G(a,c){if(!a)return null;if("function"==typeof a)return a;var b,d=/^\s*(\w+)\s*=>(.+)$/.exec(a);if(d)b=[d[1]],a=d[2];else if(d=/^\s*\(\s*([\w\s,]*)\s*\)\s*=>(.+)$/.exec(a))b=
d[1].split(/\s*,\s*/),a=d[2];if(!b){b=[];for(d=0;d<c;++d)b.push("$"+d);d=[a].concat(b);a=k.apply(null,d)}b.push("return "+a+";");return Function.apply(null,b)}function x(a){var c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return c.test(a)?'"'+a.replace(c,function(a){var c=b[a];return c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function z(a,c){var b=function(){};b.prototype=a.prototype;c.prototype=new b;c.prototype.constructor=c}function O(a,c){var b=a?a+"=":"";if("boolean"==typeof c)return b+(c?"1":"0");if("string"==typeof c)return b+encodeURIComponent(c);if("number"==typeof c)return b+c.toString();if("object"==typeof c){var d=[];r(c).each(function(b,c){c=encodeURIComponent(c);d.push(O(a?a+"["+c+"]":c,b))});return d.join("&")}return""}function P(a,c,b){var d,e;!a||a instanceof Array?(d=!a?H:a,a=Q):a instanceof
f?(d=H,a=R):"string"==typeof a&&(a=k(a,"$","$$","@.a"));!c||c instanceof Array?(e=!c?H:c,c=Q):c instanceof f?(e=H,c=R):"string"==typeof c&&(c=k(c,"$","$$","@.a"));return{left:a,leftArg:{t:d,a:b},right:c,rightArg:{t:e,a:b}}}function D(a,c,b,d){for(var e={},h=[],g=0,p=a.length;g<p;++g){var l=2*g+1;if(c=arguments[l])if(b=arguments[l+1],b instanceof Array){if(0==a[g])for(var l=0,m=b.length;l<m;++l)b[l]="";e[c]=b}else 1>=a[g]?e[c]=b:(h.push("var "+c+"="+b+";"),e[c]=c)}e.decl=h.join("");return e}function E(a,
c){this.$o=r(this.o=[]);this.c=a;this.a=c}function I(){}function f(a){this.each=a}function q(a){this.data=a;this.rev=!1}function A(a){q.call(this,a)}function y(a){q.call(this,a)}function u(a){this.data=a}function J(a){this.data=a}function w(a){this.it=a}function K(a){this.it=a}function r(a){return a?a instanceof f?a:a.$each?new f(function(c,b){this.broken=!1===a.$each(c,b);return this}):"string"==typeof a?new A(a):a instanceof Array?new y(a):new u(a):new f(function(){return this})}var C="from",H=
[void 0,null,!1,0," ","\n","\t"],Q="@t.indexOf($)>=0",R="@t.contains($)",M=/^\s*(\w+)\s*=>(.+)$/,N=/^\s*\(\s*([\w\s,]*)\s*\)\s*=>(.+)$/,F=/"(?:[^"]|\\")*"|'(?:[^']|\\')*'|[\$@\w_#]+/g;E.prototype._getPrimitiveList=function(a,c){var b=this[a];b||(this[a]=b={});c=c.toString();var d=b[c];d||(b[c]=d=[],this.o.push({k:c,l:d}));return d};E.prototype._getList=function(a){var c=this.c,b;if(c)b="string"==typeof c?k(c,"$k","@k","@a"):"@c($k,@k,@a)";else{switch(typeof a){case "string":return this._getPrimitiveList("s",
a);case "number":return this._getPrimitiveList("n",a);case "boolean":return this._getPrimitiveList("b",a)}b="$k==@k"}if(c=this.$o.first(b,{k:a,c:c,a:this.a}))return c.l;c=[];this.o.push({k:a,l:c});return c};E.prototype.add=function(a,c){this._getList(a).push(c)};E.prototype.$each=function(a,c){this.broken=!this.$o.selectPair("from($l)","$k").each(a,c).broken;return this};I.prototype.getBucket=function(a){var c=this.cache;if(!c){this.cache=c={};var b=this;setTimeout(function(){b.cache=null},0)}var d=
c[a];d||(c[a]=d={});return d};I.prototype.get=function(a,c){return this.getBucket(a)[c]};I.prototype.set=function(a,c,b){this.getBucket(a)[c]=b};var n=new I;f.prototype.broken=!1;f.prototype.where=function(a,c){var b;"string"==typeof a?(b=n.get("($_$$_a0)",a),b||(b="("+k(a,"$","$$","@a0")+")",n.set("($_$$_a0)",a,b))):b="@pr($,$$,@a0)";var d=this;return new f(function(e,h){var g;"string"==typeof e?(g=n.get("($_$$_a)",e),g||(g="("+k(e,"$","$$","@a")+")",n.set("($_$$_a)",e,g))):g="@p($,$$,@a)";this.broken=
d.each(b+"?"+g+":0",{p:e,pr:a,a0:c,a:h}).broken;return this})};f.prototype.aggregate=function(a,c,b){var d;"string"==typeof c?(d=n.get("(c_$_$$_a)",c),d||(d="("+k(c,"@c","$","$$","@a")+")",n.set("(c_$_$$_a)",c,d))):d="@p(@c,$,$$,@a)";null===a?(a={p:c,f:!0,a:b},this.each("@f?(@f=false,@c=$,0):(@c="+d+",0)",a)):(a={c:a,a:b,p:c},this.each("(@c="+d+"),0",a));return a.c};f.prototype.all=function(a,c){var b;"string"==typeof a?(b=n.get("($_$$_a)",a),b||(b="("+k(a,"$","$$","@a")+")",n.set("($_$$_a)",a,b))):
b="@p($,$$,@a)";return!this.each("!"+b+"?false:0",{a:c,p:a}).broken};f.prototype.any=function(a,c){var b;a?"string"==typeof a?(b=n.get("($_$$_a)",a),b||(b="("+k(a,"$","$$","@a")+")",n.set("($_$$_a)",a,b))):b="@p($,$$,@a)":b="true";return this.each(b+"?false:0",{a:c,p:a}).broken};f.prototype.at=function(a){return this.skip(a).first()};f.prototype.atOrDefault=function(a,c){var b=this.at(a);return void 0===b?c:b};f.prototype.average=function(){var a={f:!0};this.each("@f?(@f=false,@s=$,@c=1,0):(@s+=$,++@c)",
a);return a.s/a.c};f.prototype.concat=function(a){var c=this;return new f(function(b,d){this.broken=!1;if(c.each(b,d).broken||a.each(b,d).broken)return this.broken=!0,this})};f.prototype.contains=function(a,c,b){var d;c?"string"==typeof c?(d=n.get("(v_$_a)",c),d||(d="("+k(c,"@v","$","@a")+")",n.set("(v_$_a)",c,d))):d="@c(@v,$,@a)":d="$==@v";a={v:a,a:b,c:c,r:!1};this.each(d+"?((@r=true),false):0",a);return a.r};f.prototype.count=function(a,c){var b;a?"string"==typeof a?(b=n.get("($_$$_a)",a),b||(b=
"("+k(a,"$","$$","@a")+")",n.set("($_$$_a)",a,b))):b="@p($,$$,@a)":b="true";var d={a:c,p:a,c:0};this.each(b+"?++@c:0",d);return d.c};f.prototype.defaultIfEmpty=function(a){var c=this;return new f(function(b,d){c.each("false").broken?this.broken=c.each(b,d).broken:("string"==typeof b&&(b=G(b,3)),this.broken=!1===b(a,0,d));return this})};f.prototype.distinct=function(a,c){var b=a?",@c,@a":"",d=[],e=this;return new f(function(c,g){var p;"string"==typeof c?(p=n.get("($_$$_a0)",c),p||(p="("+k(c,"$","$$",
"@a0")+")",n.set("($_$$_a0)",c,p))):p="@p($,$$,@a0)";this.broken=e.each("!from(@l).contains($"+b+")?(@l.push($),"+p+"):0",{c:a,l:d,p:c,a0:g}).broken;return this})};f.prototype.except=function(a,c,b){var d;d=c?",@c,@a0":"";var e=this;return new f(function(h,g){this.broken="string"==typeof h?e.each("@s.contains($"+d+")?0:("+k(h,"$","$$","@a")+")",{c:c,a0:b,s:r(a),a:g}).broken:e.each("@s.contains($"+d+")?0:@p($,$$,@a)",{c:c,a0:b,p:h,s:r(a),a:g}).broken;return this})};f.prototype.first=function(a,c){if(a)"string"==
typeof a?(b={a:c},this.each("("+k(a,"$","$$","@a")+")?(@r=$,false):0",b)):(b={a:c,p:a},this.each("@p($,$$,@a)?(@r=$,false):0",b));else{var b={};this.each("(@r=$),false",b)}return b.r};f.prototype.firstOrDefault=function(a,c,b){if(1>=arguments.length){var d=this.first();return void 0===d?a:d}d=this.first(a,b);return void 0===d?c:d};f.prototype.groupBy=function(a,c,b){var d,e,h;a&&(d=a.value,e=a.key,h=a.result);d=d||"$";e=e||"$$";return h?(a="string"==typeof h?k(h,"$","$$","@a"):"@rs($,$$,@a)",this._getGroupIterable(d,
e,c,b).selectPair(a,"$$",{rs:h,a:b})):this._getGroupIterable(d,e,c,b)};f.prototype._getGroupIterable=function(a,c,b,d){b=new E(b,d);var e=r(b),h;h="string"==typeof c?"("+k(c,"$","$$","@a")+")":"@ks($,$$,@a)";var g;g="string"==typeof a?"("+k(a,"$","$$","@a")+")":"@vs($,$$,@a)";this.each("(@k="+h+"),(@v="+g+"),@g.add(@k,@v),0",{ks:c,vs:a,g:b,a:d});return e};f.prototype.groupJoin=function(a,c,b,d,e,h){a=r(a);c="string"==typeof c?"("+k(c,"$","$$","@a")+")":"@oks($,$$,@a)";b="string"==typeof b?"("+k(b,
"$","$$","@a")+")":"@iks($,$$,@a)";b=e?"string"==typeof e?k(e,"@ok",b):"@c(@ok,"+b+")":"@ok=="+b;b=x(b);c="@i.where("+b+",{a:@a,ok:"+c+",c:@c})";if("string"==typeof d)switch(b=[],t(d,3,b)[1]){case 0:case 1:c=s(b,"$",c,"@a");break;default:c="(@w="+c+"),("+s(b,"$","@w","@a")+")"}else c="@rs($,"+c+",@a)";return this.select(c,{rs:d,i:a,a:h,c:e})};f.prototype.intersect=function(a,c,b){var d;d=c?"string"==typeof c?x(c):"@c":"null";return this.where("@t.contains($,"+d+",@a)",{t:r(a),a:b,c:c})};f.prototype.join=
function(a,c,b,d,e,h){a=r(a);var g;g="string"==typeof c?"("+k(c,"$","$$","@a")+")":"@oks($,$$,@a)";var p;p="string"==typeof b?"("+k(b,"$","$$","@a")+")":"@iks($,$$,@a)";var l;l=e?"string"==typeof e?k(e,"@ok",p):"@c(@ok,"+p+")":"@ok=="+p;l=x(l);var m;m="string"==typeof d?"("+k(d,"@ov","$","@a")+")":"@rs(@ov,$,@a)";var n=this;return new f(function(e,p){var f;if("string"==typeof e){f=[];var k=t(e,3,f),L=[],r;switch(k[0]){case 0:case 1:r=m;break;default:L.push("(@RS="+m+")"),r="@RS"}switch(k[1]){case 0:case 1:k=
"(@c++)";break;default:L.push("(@cc=@c++)"),k="@cc"}L.push("("+s(f,r,k,"@a0")+")");f=L.join(",")}else f="@p("+m+",@c++,@a0)";this.broken=n.each("(@ok="+g+"),(@ov=$),@i.where("+l+",@).each("+x(f)+",@)",{i:a,oks:c,iks:b,rs:d,p:e,a:h,a0:p,c:0}).broken;return this})};f.prototype.last=function(a,c){if(a)"string"==typeof a?(b={a:c},this.each("("+k(a,"$","$$","@a")+")?@r=$:0",b)):(b={a:c,p:a},this.each("@p($,$$,@a)?@r=$:0",b));else{var b={};this.each("@r=$",b)}return b.r};f.prototype.lastOrDefault=function(a,
c,b){if(1>=arguments.length){var d=this.last();return void 0===d?a:d}d=this.last(a,b);return void 0===d?c:d};f.prototype.max=function(a,c){if(!a)return this.aggregate(null,"#0>#1?#0:#1");var b;b="string"==typeof a?"("+k(a,"$","$$","@a")+")":"@s($,$$,@a)";var d={f:!0,s:a,a:c};this.each("@f?((@f=false),(@r=$),(@m="+b+"),0):((@v="+b+"),(@v>@m?((@m=@v),(@r=$)):0),0)",d);return d.r};f.prototype.min=function(a,c){if(!a)return this.aggregate(null,"#0<#1?#0:#1");var b;b="string"==typeof a?"("+k(a,"$","$$",
"@a")+")":"@s($,$$,@a)";var d={f:!0,s:a,a:c};this.each("@f?((@f=false),(@r=$),(@m="+b+"),0):((@v="+b+"),(@v<@m?((@m=@v),(@r=$)):0),0)",d);return d.r};f.prototype.orderBy=function(a,c,b){return(new w(this))._addContext(a||"$",c,1,b)};f.prototype.orderByDesc=function(a,c,b){return(new w(this))._addContext(a||"$",c,-1,b)};f.prototype.reverse=function(){var a=this;return new f(function(c,b){var d=[];a.each("@push($$),@push($),0",d);if("string"==typeof c){var e=[],h=t(c,3,e),g,f,l;switch(h[0]){case 0:case 1:g=
"";f="l[(i-1)*2+1]";break;default:g="var v=l[(i-1)*2+1];",f="v"}switch(h[1]){case 0:case 1:h="";l="l[(i-1)*2]";break;default:h="var k=l[(i-1)*2];",l="k"}this.broken=(new Function("l","a","for(var i=l.length/2;i>0;--i){"+h+g+"if(("+s(e,f,l,"a")+")===false){return true;}}return false;"))(d,b)}else{this.broken=!1;for(e=d.length/2;0<e;--e)if(!1===c(d[2*(e-1)+1],d[2*(e-1)],b)){this.broken=!0;break}}return this})};f.prototype.select=function(a,c){var b=this,d;"string"==typeof a?(d=n.get("($_$$_a0)",a),
d||(d="("+k(a,"$","$$","@a0")+")",n.set("($_$$_a0)",a,d))):d="@s($,$$,@a0)";return new f(function(e,h){if("string"==typeof e){var g=[],f=t(e,3,g),l=[],m;switch(f[0]){case 0:m="";break;case 1:m=d;break;default:l.push("(@v="+d+")"),m="@v"}switch(f[1]){case 0:f="";break;case 1:f="(@i++)";break;default:l.push("(@j=@i++)"),f="@j"}l.push(s(g,m,f,"@a"));this.broken=b.each(l.join(","),{s:a,a0:c,a:h,i:0}).broken}else this.broken=b.each("@p("+d+",@i++,@a)",{s:a,a0:c,a:h,i:0,p:e}).broken;return this})};f.prototype.selectMany=
function(a,c){var b;b="string"==typeof a?k(a,"$","$$","@a"):"@s($,$$,@a)";var d=this;return new f(function(e,h){var g;if("string"==typeof e)switch(g=[],t(e,3,g)[1]){case 0:case 1:g=s(g,"$","(@i++)","@a0");break;default:g="(@j=@i++),("+s(g,"$","@j","@a0")+")"}else g="@p($,@i++,@a0)";this.broken=d.each("from("+b+").each("+x(g)+",@)",{s:a,a:c,a0:h,i:0,p:e});return this})};f.prototype.selectPair=function(a,c,b){var d=this,e,h;"string"==typeof a?(e=n.get("($_$$_a0)",a),e||(e="("+k(a,"$","$$","@a0")+")",
n.set("($_$$_a0)",a,e))):e="@vs($,$$,@a0)";"string"==typeof c?(h=n.get("($_$$_a0)",c),h||(h="("+k(c,"$","$$","@a0")+")",n.set("($_$$_a0)",c,h))):h="@ks($,$$,@a0)";return new f(function(g,f){var l;if("string"==typeof g){l=[];var m=t(g,3,l),n,v=[];switch(m[0]){case 0:case 1:n=e;break;default:v.push("(@VS="+e+")"),n="@VS"}switch(m[1]){case 0:case 1:m=h;break;default:v.push("(@KS="+h+")"),m="@KS"}v.push(s(l,n,m,"@a"));l=v.join(",")}else l="@p("+e+","+h+",@a)";this.broken=d.each(l,{a0:b,a:f,p:g,vs:a,ks:c}).broken;
return this})};f.prototype.sequenceEqual=function(a,c,b){var d;d=c?"string"==typeof c?k(c,"#0","#1","@a"):"@c(#0,#1,@a)":"#0==#1";return this.zip(a,d,{a:b,c:c}).all("$==true")};f.prototype.single=function(a,c){var b=!a?this.take(2):this.where(a).take(2);if(1==b.count())return b.first()};f.prototype.singleOrDefault=function(a,c,b){var d;1>=arguments.length?(d=this.take(2),c=a):d=this.where(a).take(2);var e=d.count();if(0==e)return c;if(1==e)return d.first();throw Error("The sequence has more than one element satisfying the condition.");
};f.prototype.skip=function(a){if(0>=a)return this;var c=this;return new f(function(b,d){var e;"string"==typeof b?(e=n.get("($_$$_a)",b),e||(e="("+k(b,"$","$$","@a")+")",n.set("($_$$_a)",b,e))):e="@p($,$$,@a)";this.broken=c.each("@c==0?"+e+":--@c",{p:b,a:d,c:a}).broken;return this})};f.prototype.skipWhile=function(a,c){var b;"string"==typeof a?(b=n.get("($_$$_a)",a),b||(b="("+k(a,"$","$$","@a")+")",n.set("($_$$_a)",a,b))):b="@pr($,$$,@a)";var d=this;return new f(function(e,h){var g;"string"==typeof e?
(g=n.get("($_$$_a0)",e),g||(g="("+k(e,"$","$$","@a0")+")",n.set("($_$$_a0)",e,g))):g="@p($,$$,@a0)";this.broken=d.each("@f||(@f=!"+b+")?"+g+":0",{pr:a,f:!1,a:c,a0:h}).broken;return this})};f.prototype.sum=function(){return this.aggregate(null,"#0+#1")};f.prototype.take=function(a){if(0==a)return r();if(0>a)return this.reverse().take(-a).reverse();var c=this;return new f(function(b,d){var e;"string"==typeof b?(e=n.get("($_$$_a)",b),e||(e="("+k(b,"$","$$","@a")+")",n.set("($_$$_a)",b,e))):e="@p($,$$,@a)";
var h={i:0,p:b,a:d,b:!1};this.broken=c.each("(@i++<"+a+")?"+e+":(@b=true,false)",h).broken&&!h.b;return this})};f.prototype.takeWhile=function(a,c){var b;"string"==typeof a?(b=n.get("($_$$_a)",a),b||(b="("+k(a,"$","$$","@a")+")",n.set("($_$$_a)",a,b))):b="@pr($,$$,@a)";var d=this;return new f(function(e,h){var g;"string"==typeof e?(g=n.get("($_$$_a0)",e),g||(g="("+k(e,"$","$$","@a0")+")",n.set("($_$$_a0)",e,g))):g="@p($,$$,@a0)";var f={p:e,pr:a,a:c,a0:h,b:!1};this.broken=d.each(b+"?"+g+":(@b=true,false)",
f).broken&&!f.b;return this})};f.prototype.toArray=function(){var a=[];this.each("@push($)",a);return a};f.prototype.toDictionary=function(){var a={};this.each("@[$$]=$",a);return a};f.prototype.toJSON=function(a){function c(d){var e=typeof d;return"string"==e?x(d):"number"==e||"boolean"==e?d.toString():"function"==e?c(d()):b.contains(d)||(d instanceof y||d instanceof u)&&b.contains(d.data)?"null":r(d).toJSON(a)}a||(a=[]);var b=r(a),d="number"==typeof this.select("$$").first();a.push(this);if(d){var e=
[];this.each(function(a){e.push(c(a))});d="["+e.join(", ")+"]"}else e=[],this.each(function(a,b){e.push(x(b.toString())+": "+c(a))}),d="{"+e.join(", ")+"}";a.pop(this);return d};f.prototype.toString=function(a){return this.toArray().join(a||"")};f.prototype.toURLEncoded=function(){return O(null,this)};f.prototype.trim=function(a,c,b){a=P(a,c,b);return this.skipWhile(a.left,a.leftArg).reverse().skipWhile(a.right,a.rightArg).reverse()};f.prototype.union=function(a,c,b){var d=[],e=this;return new f(function(h,
g){var f;if("string"==typeof h)switch(f=[],t(h,3,f)[1]){case 0:case 1:f=s(f,"$","(@b.length-1)","@a0");break;default:f="(@bb=@b.length-1),("+s(f,"$","@bb","@a0")+")"}else f="@p($,@b.length-1,@a0)";f="from(@b).contains($,@c,@a)?0:(@b.push($),"+f+",0)";var l={c:c,b:d,p:h,a0:g,a:b};if(e.each(f,l).broken)return this.broken=!0,this;r(a).each(f,l).broken&&(this.broken=!0);return this})};f.prototype.zip=function(a,c,b){var d;if("string"==typeof c){var e=[],h=t(c,5,e),g,p=[];switch(h[0]){case 0:case 1:g=
"@d[@i*2+1]";break;default:p.push("(@V=@d[@i*2+1])"),g="@V"}switch(h[2]){case 0:case 1:h="@d[@i*2]";break;default:p.push("(@K=@d[@i*2])"),h="@K"}p.push(s(e,g,"$",h,"$$","@a"));d="("+p.join(",")+")"}else d="@rs(@d[@i*2+1],$,@d[@i*2],$$,@a)";var l=this;return new f(function(e,h){var g=[];l.each("@push($$),@push($),0",g);var f;if("string"==typeof e){f=[];var p=t(e,3,f),n,k=[];switch(p[0]){case 0:case 1:n=d;break;default:k.push("(@RS="+d+")"),n="@RS"}switch(p[1]){case 0:case 1:p="(@k++)";break;default:k.push("(@kk=@k++)"),
p="@kk"}k.push(s(f,n,p,"@a0"));f="("+k.join(",")+")"}else f="@p("+d+",@k++,@a0)";this.broken=r(a).each("@i>="+g.length/2+"?false:@r="+f+",++@i,@r",{a:b,a0:h,k:0,i:0,d:g,p:e,rs:c}).broken;return this})};z(f,q);q.prototype.initRegion=function(){var a=this.region;a||(this.region=a={queries:null,measured:!1,start:null,end:null,take:null,takeArg:null});return a};q.prototype.addRegionQuery=function(a,c,b){var d=this.initRegion(),e=d.queries;e||(d.queries=e=[]);e.push(a);e.push(c);e.push(b);d.start=d.end=
null;d.measured=!1;return this};q.prototype.clone=function(){var a=new this.constructor(this.data),c=this.region;if(c){var b=a.region={measured:c.measured,start:c.start,end:c.end,take:c.take,takeArg:c.takeArg};if(c=c.queries)b.queries=r(c).toArray()}return a};q.prototype.reverseRegion=function(){var a=this.initRegion();a&&(a.take&&(a.measured=!1),a.take=a.takeArg=null);this.rev=!this.rev;return this};q.prototype.measureRegion=function(){var a=this.initRegion();if(!a.measured){var c=this.data,b=a.start,
d=a.end;null==b&&(b=0);null===d&&(d=c.length);a.takeLeft=a.takeLeftArg=null;var e=a.queries;if(e){for(var h=[],g=0,f=e.length;g<f;g+=3){var l=e[g],m=e[g+1],n=e[g+2];if("skipLeft"==l)if("number"==typeof m)h.push("s=Math.min(e,s+"+m+");");else if("string"==typeof m){var l=[],k=t(m,3,l),k=D(k,"v",this.lambdaGetItem("d","s"),null,null,"a","q["+(g+2)+"]");h.push("for(;s<e;++s){",k.decl,"if(!(",s(l,k.v,"s",k.a),")){break;}}")}else h.push("for(;s<e&&q[",g+1,"](",this.lambdaGetItem("d","s"),",s,q[",g+2,"]);++s);");
else"skipRight"==l?"number"==typeof m?h.push("e=Math.max(s,e-",m,");"):"string"==typeof m?(l=[],k=t(m,3,l),0==k[1]?(m="",n="e-1"):(m="var _i=e-1;",n="_i"),k=D(k,"v",this.lambdaGetItem("d",n),null,null,"a","q["+(g+2)+"]"),h.push("for(;s<e;--e){",m,k.decl,"if(!(",s(l,k.v,n,k.a),")){break;}}")):h.push("for(;s<e;--e){var _i=e-1;","if(!q[",g+1,"](",this.lambdaGetItem("d","_i"),",_i,q[",g+2,"])){break;}}"):"takeLeft"==l?"number"==typeof m?h.push("e=Math.min(e,s+",m,");"):g==f-3&&!this.rev?(a.take=m,a.takeArg=
n):"string"==typeof m?(l=[],k=t(m,3,l),k=D(k,"_v",this.lambdaGetItem("d","e"),null,null,"_a","q["+(g+2)+"]"),h.push("for(var _e2=e,e=s;e<_e2;++e){",k.decl,"if(!(",s(l,k._v,"e",k._a),")){break;}}")):h.push("for(var _e2=e,e=s;e<_e2;++e){","if(!q[",g+1,"](",this.lambdaGetItem("d","e"),",e,q[",g+2,"])){break;}}"):"takeRight"==l&&("number"==typeof m?h.push("s=Math.max(s,e-",m,");"):g==f-3&&this.rev?(a.take=m,a.takeArg=n):"string"==typeof m?(l=[],k=t(m,3,l),0==k[1]?(m="",n="s-1"):(m="var _i=s-1;",n="_i"),
k=D(k,"_v",this.lambdaGetItem("d",n),null,null,"_a","q["+(g+2)+"]"),h.push("for(var _s2=s,s=e;s>_s2;--s){",m,k.decl,"if(!(",s(l,k._v,n,k._a),")){break;}}")):h.push("for(var _s2=s,s=e;s>_s2;--s){var _i=s-1;","if(!q[",g+1,"](",this.labmdaGetItem("d","_i"),",_i,q[",g+2,"])){break;}}"))}h.push("r.start=s;r.end=e;");(new Function("d","r","q","s","e",h.join("")))(c,a,e,b,d)}else a.start=b,a.end=d;a.measured=!0}return a};q.prototype.each=function(a,c){var b=this.data,d=this.measureRegion(),e=d.take,h=d.takeArg,
f;"function"==typeof a&&(f=a,a="_p($,$$,@)");e&&(a="string"==typeof e?"!("+k(e,"$","$$","_tla")+")?_b=false:"+a:"!_tl($,$$,_tla)?_b=false:"+a);var p=this.dataType+(this.rev?"_reversed":""),l=n.get("each_"+p,a);if(!l){var l=[],m=t(a,3,l),q,v;this.rev?0==m[1]?(q="",v="_e-1"):(q="var _i=_e-1;",v="_i"):(q="",v="_s");var S;S=this.rev?"--_e":"++_s";m=D(m,"_v",this.lambdaGetItem("s",v,"_l"));l=new Function(C,"s","_l","_s","_e","a","_tl","_tla","_p",["var _b=true;for(;_s<_e;",S,"){",q,m.decl,"if((",s(l,m._v,
v,"a"),")===false){return _b;}}return false;"].join(""));n.set("each_"+p,a,l)}this.broken=l(r,b,b.length,d.start,d.end,c,e,h,f);return this};q.prototype.at=function(a){var c=this.measureRegion();return this.rev?this.getItem(this.data,c.end-a):this.getItem(this.data,c.start+a)};q.prototype.count=function(a,c){if(!a){var b=this.measureRegion();if(!b.take)return b.end-b.start}return f.prototype.count.call(this,a,c)};q.prototype.any=function(a,c){if(!a){var b=this.measureRegion();if(!b.take)return b.start<
b.end}return f.prototype.any.call(this,a,c)};q.prototype.first=function(a,c){if(!a){var b=this.measureRegion();if(!b.take){var d=b.start,b=b.end;if(d<b)return this.rev?this.getItem(this.data,b-1):this.getItem(this.data,d);return}}return f.prototype.first.call(this,a,c)};q.prototype.last=function(a,c){if(!a){var b=this.measureRegion();if(!b.take){var d=b.start,b=b.end;if(d<b)return this.rev?this.getItem(this.data,d):this.getItem(this.data,b-1);return}}return f.prototype.last.call(this,a,c)};q.prototype.orderBy=
function(a,c,b){return(new K(this))._addContext(a||"$",c,1,b)};q.prototype.orderByDesc=function(a,c,b){return(new K(this))._addContext(a||"$",c,-1,b)};q.prototype.reverse=function(){return this.clone().reverseRegion()};q.prototype.skip=function(a){return this.clone().addRegionQuery(!this.rev?"skipLeft":"skipRight",a,null)};q.prototype.skipWhile=function(a,c){return this.clone().addRegionQuery(!this.rev?"skipLeft":"skipRight",a,c)};q.prototype.take=function(a){return 0>a?this.clone().addRegionQuery(!this.rev?
"takeRight":"takeLeft",-a,null):this.clone().addRegionQuery(!this.rev?"takeLeft":"takeRight",a,null)};q.prototype.takeWhile=function(a,c){return this.clone().addRegionQuery(!this.rev?"takeLeft":"takeRight",a,c)};q.prototype.toArray=function(){var a=this.measureRegion();if(!a.take){var c=this.getItem,b=this.data,d=a.start,a=a.end,e=Array(a-d);if(this.rev)for(h=a;h>d;--h)e[a-h]=c(b,h-1);else for(var h=d;h<a;++h)e[h-d]=c(b,h);return e}return f.prototype.toArray.call(this)};q.prototype.trim=function(a,
c,b){a=P(a,c,b);c=this.clone();c.addRegionQuery(!this.rev?"skipLeft":"skipRight",a.left,a.leftArg);c.addRegionQuery(!this.rev?"skipRight":"skipLeft",a.right,a.rightArg);return c};q.prototype.zip=function(a,c,b){var d=this.rev,e,h=!d?"@i":"@l-@i-1";if("string"==typeof c){var g=[],k=t(c,5,g),l=[];d&&0<k[1]&&(l.push("(@.ii="+h+")"),h="@.ii");var m=this.lambdaGetItem("@d",h);1<k[0]&&(l.push("(@V="+m+")"),m="@V");l.push("("+s(g,m,"$",h,"$$","@a")+")");e="("+l.join(",")+")"}else e="@rs("+m+",$,"+h+",$$,@a)";
var n=this;return new f(function(d,h){var f=n.data,g=f.length,l;if("string"==typeof d){l=[];var k=t(d,3,l),m,p=[];switch(k[0]){case 0:case 1:m=e;break;default:p.push("(@RS="+e+")"),m="@RS"}switch(k[1]){case 0:case 1:k="(@k++)";break;default:p.push("(@kk=@k++)"),k="@kk"}p.push(s(l,m,k,"@a0"));l="("+p.join(",")+")"}else l="@p("+e+",@k++,@a0)";f={a:b,a0:h,k:0,i:0,d:f,l:g,p:d,rs:c,b:!0};this.broken=r(a).each("@.i>=@.l?@.b=false:@.r="+l+",++@.i,@.r",f).broken&&!f.nb;return this})};z(q,A);A.prototype.dataType=
"string";A.prototype.lambdaGetItem=function(a,c){return a+".charAt("+c+")"};A.prototype.getItem=function(a,c){return a.charAt(c)};A.prototype.toString=function(a){if(!a&&!this.rev){var c=this.data,b=this.measureRegion();if(!b.take)return a=b.start,b=b.end,0==a&&b==c.length?c:c.substring(a,b)}return f.prototype.toString.call(this,a)};A.prototype.toJSON=function(){return x(this.data)};z(q,y);y.prototype.dataType="array";y.prototype.lambdaGetItem=function(a,c){return a+"["+c+"]"};y.prototype.getItem=
function(a,c){return a[c]};y.prototype.toJSON=function(a){a?a.push(this.data):a=[this.data];var c=f.prototype.toJSON.call(this,a);a.pop();return c};z(f,u);u.prototype.each=function(a,c){var b=this.data;if("function"==typeof a){this.broken=!1;for(var d in b)if(!1===a(b[d],d,c)){this.broken=!0;break}}else{d=n.get("each_o",a);if(!d){d=[];var e,h;switch(t(a,3,d)[0]){case 0:case 1:e="";h="d[k]";break;default:e="var v=d[k];",h="v"}d=new Function(C,"d","a","for(var k in d){"+e+"if(("+s(d,h,"k","a")+")===false){return true;}}return false;");
n.set("each_o",a,d)}this.broken=d(r,b,c)}return this};u.prototype.at=function(a){return this.skip(a).first()};u.prototype.reverse=function(){return new J(this.data)};u.prototype.toJSON=y.prototype.toJSON;z(u,J);J.prototype.each=function(a,c){var b=this.data,d=[],e;for(e in b)d.push(e),d.push(b[e]);if("string"==typeof a){b=n.get("each_or",a);if(!b){var b=[],h=t(a,3,b),f,k;switch(h[0]){case 0:case 1:e="";f="r[ii+1]";break;default:e="var v=r[ii+1];",f="v"}switch(h[1]){case 0:case 1:h="";k="r[ii]";break;
default:h="var k=r[ii];",k="k"}b=new Function(C,"r","a","for(var i=r.length/2;i>0;--i){var ii=(i-1)*2;"+e+h+"if(("+s(b,f,k,"a")+")===false){return true;}}return false;");n.set("each_or",a,b)}this.broken=b(r,d,c)}else{this.broken=!1;for(b=d.length/2;0<b;--b)if(e=2*(b-1),!1===a(d[e+1],d[e],c)){this.broken=!0;break}}return this};J.prototype.reverse=function(){return new u(this.data)};z(u,w);w.prototype.clone=function(){var a=new this.constructor(this.it),c=this.context;c&&(a.context=r(c).toArray());
return a};w.prototype._addContext=function(a,c,b,d){var e=this.context;e||(this.context=e=[]);e.push({keySelector:G(a,3),comparer:G(c,3),asc:b,arg:d});return this};w.prototype.each=function(a,c){function b(a,b){if(h)for(var c=0,e=h.length;c<e;++c){var f=h[c],g=f.keySelector(d[2*a+1],d[2*a],f.arg),k=f.keySelector(d[2*b+1],d[2*b],f.arg),f=f.comparer?f.asc*f.comparer(g,k,f.arg):g==k?0:g<k?-f.asc:f.asc;if(0!=f)return f}return a==b?0:a<b?-1:1}var d=[];this.it.each("@push($$),@push($),0",d);var e=r.range(d.length/
2).toArray(),h=this.context;e.sort(b);if("string"==typeof a){b=n.get("each_ord",a);if(!b){var f=[],k=t(a,3,f),l,m,q;switch(k[0]){case 0:case 1:l="";m="r[n+1]";break;default:l="var v=r[n+1];",m="v"}switch(k[1]){case 0:case 1:k="";q="r[n]";break;default:k="var k=r[n];",q="k"}b=new Function(C,"l","r","a","for(var i=0,c=l.length;i<c;++i){var n=l[i]*2;"+l+k+"if(("+s(f,m,q,"a")+")===false)return true;}return false;");n.set("each_ord",a,b)}this.broken=b(r,e,d,c)}else{this.broken=!1;f=0;for(l=e.length;f<
l;++f)if(m=2*e[f],!1===a(d[m+1],d[m],c)){this.broken=!0;break}}return this};w.prototype.thenBy=function(a,c,b){return this.clone()._addContext(a,c,1,b)};w.prototype.thenByDesc=function(a,c,b){return this.clone()._addContext(a,c,-1,b)};z(w,K);K.prototype.each=function(a,c){function b(a,b){if(f)for(var c=0,d=f.length;c<d;++c){var g=f[c],k=g.keySelector(e[a],a,g.arg),l=g.keySelector(e[b],b,g.arg),g=g.comparer?g.asc*g.comparer(k,l,g.arg):k==l?0:k<l?-g.asc:g.asc;if(0!=g)return g}return a==b?0:a<b?-1:1}
var d=this.it.select("$$").toArray(),e=this.it.data,f=this.context;d.sort(b);if("string"==typeof a){b=n.get("each_ordered_random_access",a);if(!b){var g=[],k=t(a,3,g),l,m,q;switch(k[1]){case 0:l="";q="l[i]";break;default:l="var k=l[i];",q="k"}switch(k[0]){case 0:case 1:k="";m="r["+q+"]";break;default:k="var v=r["+q+"];",m="v"}b=new Function(C,"l","r","a","for(var i=0,c=l.length;i<c;++i){"+l+k+"if(("+s(g,m,q,"a")+")===false)return true;}return false;");n.set("each_ordered_random_access",a,b)}this.broken=
b(r,d,e,c)}else{this.broken=!1;g=0;for(l=d.length;g<l;++g)if(q=d[g],!1===a(e[q],q,c)){this.broken=!0;break}}return this};r.range=function(a,c,b){switch(arguments.length){case 1:c=a;a=0;b=1;break;case 2:b=c>a?1:-1}return new f(function(d,e){if("string"==typeof d){var f=0<b?"each_ru":"each_rd",g=n.get(f,d);g||(g=new Function("s","e","st","a","for(var i=s;i"+(0<b?"<":">")+"e;i+=st){if(("+k(d,"i","i","a")+")===false)return true;}return false;"),n.set(f,d,g));this.broken=g(a,c,b,e)}else if(this.broken=
!1,0<b)for(f=a;f<c;f+=b){if(!1===d(f,f,e)){this.broken=!0;break}}else for(f=a;f>c;f+=b)if(!1===d(f,f,e)){this.broken=!0;break}return this})};r.repeat=function(a,c){return new f(function(b,d){if("string"==typeof b){var e=n.get("each_rpt",b);e||(e=new Function("c","e","a","for(var i=0;i<c;++i){if(("+k(b,"e","i","a")+")===false)return true;}return false;"),n.set("each_rpt",b,e));this.broken=e(c,a,d)}else{this.broken=!1;for(e=0;e<c;++e)if(!1===b(a,e,d)){this.broken=!0;break}}return this})};r.setAlias=
function(a){C=a};r.lambda={replace:k,parse:G,getUseCount:t,join:s};module&&module.exports?module.exports=r:window.from=r})();
