/**
 * from.js for node v2.0.0
 * Copyright 2012-2013 suckgamony@gmail.com
 */
(function(){function C(a,d,b){if(a.length==d)return b;a=a.substr(d);return/^[0-9]+$/.exec(a)?b+"["+a+"]":b+"."+a}function s(a,d,b){var c,e=I.exec(a);e?(c=[e[1]],a=e[2],d=Array(1)):(e=J.exec(a))?(c=e[1].split(/\s*,\s*/),a=e[2],d=Array(c.length)):d=Array(d);for(var e=0,k=d.length;e<k;++e)d[e]=0;var k=0,n="";if(c)for(;e=E.exec(a);)for(var m=e[0],l=0,f=c.length;l<f;++l){if(m==c[l]){++d[l];b&&(b.push(a.substring(k,e.index)),b.push(l),k=e.index+m.length);break}}else for(c="";e=E.exec(a);){m=e[0];f=m.charAt(0);
l=null;if("$"==f)if(f=m.length,2<=f&&"$"==m[1])++d[1],b&&(l=1,c=C(m,2,""));else{if(1==f||!(m in global))++d[0],b&&(l=0,c=C(m,1,""))}else"@"==f?(f=d.length-1,++d[f],b&&(l=f,c=C(m,1,""))):"#"==f&&(f=parseInt(m.substr(1)),++d[f],b&&(l=f,c=""));b&&null!==l&&(b.push(n+a.substring(k,e.index)),b.push(l),k=e.index+m.length,n=c,c="")}b&&b.push(n+a.substring(k,a.length));return d}function h(a,d,b){var c,e=I.exec(a);if(e)c=[e[1]],a=e[2];else if(e=J.exec(a))c=e[1].split(/\s*,\s*/),a=e[2];var k=arguments,n=0<
k.length?k[k.length-1]:"";return c?a.replace(E,function(a){for(var b=0,d=c.length;b<d;++b)if(a==c[b])return k[b+1];return a}):a.replace(E,function(a){var c=a.charAt(0);if("$"==c){c=a.length;if(2<=c&&"$"==a[1])return C(a,2,b);if(1==c||!(a in global))return C(a,1,d)}else{if("@"==c)return C(a,1,n);if("#"==c)return k[parseInt(a.substr(1))+1]}return a})}function r(a,d,b){for(var c=1,e=a.length;c<e;c+=2){var k=a[c];"number"==typeof k&&(a[c]=arguments[k+1])}return a.join("")}function F(a,d){if(!a)return null;
if("function"==typeof a)return a;var b,c=/^\s*(\w+)\s*=>(.+)$/.exec(a);if(c)b=[c[1]],a=c[2];else if(c=/^\s*\(\s*([\w\s,]*)\s*\)\s*=>(.+)$/.exec(a))b=c[1].split(/\s*,\s*/),a=c[2];if(!b){b=[];for(c=0;c<d;++c)b.push("$"+c);c=[a].concat(b);a=h.apply(null,c)}b.push("return "+a+";");return Function.apply(global,b)}function w(a){var d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",
'"':'\\"',"\\":"\\\\"};return d.test(a)?'"'+a.replace(d,function(a){var d=b[a];return d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function A(a,d){var b=function(){};b.prototype=a.prototype;d.prototype=new b}function K(a,d){var b=a?a+"=":"";if("boolean"==typeof d)return b+(d?"1":"0");if("string"==typeof d)return b+encodeURIComponent(d);if("number"==typeof d)return b+d.toString();if("object"==typeof d){var c=[];q(d).each(function(b,d){d=encodeURIComponent(d);c.push(K(a?
a+"["+d+"]":d,b))});return c.join("&")}return""}function D(a,d){this.$o=q(this.o=[]);this.c=a;this.a=d}function G(){}function f(a){this.each=a}function t(a){this.str=a}function p(a){this.data=a}function v(a){this.data=a}function x(a){this.str=a}function y(a){this.data=a}function H(a){this.data=a}function B(a){this.Iterable=a;this.context=[]}function q(a){return a?a instanceof f?a:a.$each?new f(function(d,b){this.broken=!1===a.$each(d,b);return this}):"string"==typeof a?new t(a):a instanceof Array?
new p(a):new v(a):new f(function(){return this})}var z="from",I=/^\s*(\w+)\s*=>(.+)$/,J=/^\s*\(\s*([\w\s,]*)\s*\)\s*=>(.+)$/,E=/"(?:[^"]|\\")*"|'(?:[^']|\\')*'|[\$@\w_#]+/g;D.prototype._getPrimitiveList=function(a,d){var b=this[a];b||(this[a]=b={});d=d.toString();var c=b[d];c||(b[d]=c=[],this.o.push({k:d,l:c}));return c};D.prototype._getList=function(a){var d=this.c,b;if(d)b="string"==typeof d?h(d,"$k","@k","@a"):"@c($k,@k,@a)";else{switch(typeof a){case "string":return this._getPrimitiveList("s",
a);case "number":return this._getPrimitiveList("n",a);case "boolean":return this._getPrimitiveList("b",a)}b="$k==@k"}if(d=this.$o.first(b,{k:a,c:d,a:this.a}))return d.l;d=[];this.o.push({k:a,l:d});return d};D.prototype.add=function(a,d){this._getList(a).push(d)};D.prototype.$each=function(a,d){this.broken=!this.$o.selectPair("from($l)","$k").each(a,d).broken;return this};G.prototype.getBucket=function(a){var d=this.cache;if(!d){this.cache=d={};var b=this;setTimeout(function(){b.cache=null},0)}var c=
d[a];c||(d[a]=c={});return c};G.prototype.get=function(a,d){return this.getBucket(a)[d]};G.prototype.set=function(a,d,b){this.getBucket(a)[d]=b};var g=new G;f.prototype.broken=!1;f.prototype.where=function(a,d){var b;"string"==typeof a?(b=g.get("($_$$_a0)",a),b||(b="("+h(a,"$","$$","@a0")+")",g.set("($_$$_a0)",a,b))):b="@pr($,$$,@a0)";var c=this;return new f(function(e,k){var n;"string"==typeof e?(n=g.get("($_$$_a)",e),n||(n="("+h(e,"$","$$","@a")+")",g.set("($_$$_a)",e,n))):n="@p($,$$,@a)";this.broken=
c.each(b+"?"+n+":0",{p:e,pr:a,a0:d,a:k}).broken;return this})};f.prototype.aggregate=function(a,d,b){var c;"string"==typeof d?(c=g.get("(c_$_$$_a)",d),c||(c="("+h(d,"@c","$","$$","@a")+")",g.set("(c_$_$$_a)",d,c))):c="@p(@c,$,$$,@a)";null===a?(a={p:d,f:!0,a:b},this.each("@f?(@f=false,@c=$,0):(@c="+c+",0)",a)):(a={c:a,a:b,p:d},this.each("(@c="+c+"),0",a));return a.c};f.prototype.all=function(a,d){var b;"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):
b="@p($,$$,@a)";return!this.each("!"+b+"?false:0",{a:d,p:a}).broken};f.prototype.any=function(a,d){var b;a?"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@p($,$$,@a)":b="true";return this.each(b+"?false:0",{a:d,p:a}).broken};f.prototype.at=function(a){return this.skip(a).first()};f.prototype.atOrDefault=function(a,d){var b=this.at(a);return void 0===b?d:b};f.prototype.average=function(){var a={f:!0};this.each("@f?(@f=false,@s=$,@c=1,0):(@s+=$,++@c)",
a);return a.s/a.c};f.prototype.concat=function(a){var d=this;return new f(function(b,c){this.broken=!1;if(d.each(b,c).broken||a.each(b,c).broken)return this.broken=!0,this})};f.prototype.contains=function(a,d,b){var c;d?"string"==typeof d?(c=g.get("(v_$_a)",d),c||(c="("+h(d,"@v","$","@a")+")",g.set("(v_$_a)",d,c))):c="@c(@v,$,@a)":c="$==@v";a={v:a,a:b,c:d,r:!1};this.each(c+"?((@r=true),false):0",a);return a.r};f.prototype.count=function(a,d){var b;a?"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b=
"("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@p($,$$,@a)":b="true";var c={a:d,p:a,c:0};this.each(b+"?++@c:0",c);return c.c};f.prototype.defaultIfEmpty=function(a){var d=this;return new f(function(b,c){d.each("false").broken?this.broken=d.each(b,c).broken:("string"==typeof b&&(b=F(b,3)),this.broken=!1===b(a,0,c));return this})};f.prototype.distinct=function(a,d){var b=a?",@c,@a":"",c=[],e=q(c),k=this;return new f(function(d,f){var l;"string"==typeof d?(l=g.get("($_$$_a0)",d),l||(l="("+h(d,
"$","$$","@a0")+")",g.set("($_$$_a0)",d,l))):l="@p($,$$,@a0)";this.broken=k.each("!@ll.contains($"+b+")?(@l.push($),"+l+"):0",{c:a,ll:e,l:c,p:d,a0:f}).broken;return this})};f.prototype.except=function(a,d,b){var c;c=d?",@c,@a0":"";var e=this;return new f(function(k,n){this.broken="string"==typeof k?e.each("@s.contains($"+c+")?0:("+h(k,"$","$$","@a")+")",{c:d,a0:b,s:q(a),a:n}).broken:e.each("@s.contains($"+c+")?0:@p($,$$,@a)",{c:d,a0:b,p:k,s:q(a),a:n}).broken;return this})};f.prototype.first=function(a,
d){if(a)"string"==typeof a?(b={a:d},this.each("("+h(a,"$","$$","@a")+")?(@r=$,false):0",b)):(b={a:d,p:a},this.each("@p($,$$,@a)?(@r=$,false):0",b));else{var b={};this.each("(@r=$),false",b)}return b.r};f.prototype.firstOrDefault=function(a,d,b){if(1>=arguments.length){var c=this.first();return void 0===c?a:c}c=this.first(a,b);return void 0===c?d:c};f.prototype.groupBy=function(a,d,b){var c=a.value||"$",e=a.key||"$$";if(a=a.result){var k;k="string"==typeof a?h(a,"$","$$","@a"):"@rs($,$$,@a)";return this._getGroupIterable(c,
e,d,b).selectPair(k,"$$",{rs:a,a:b})}return this._getGroupIterable(c,e,d,b)};f.prototype._getGroupIterable=function(a,d,b,c){b=new D(b,c);var e=q(b),k;k="string"==typeof d?"("+h(d,"$","$$","@a")+")":"@ks($,$$,@a)";var n;n="string"==typeof a?"("+h(a,"$","$$","@a")+")":"@vs($,$$,@a)";this.each("(@k="+k+"),(@v="+n+"),@g.add(@k,@v),0",{ks:d,vs:a,g:b,a:c});return e};f.prototype.groupJoin=function(a,d,b,c,e,k){a=q(a);d="string"==typeof d?"("+h(d,"$","$$","@a")+")":"@oks($,$$,@a)";b="string"==typeof b?"("+
h(b,"$","$$","@a")+")":"@iks($,$$,@a)";b=e?"string"==typeof e?h(e,"@ok",b):"@c(@ok,"+b+")":"@ok=="+b;b=w(b);d="@i.where("+b+",{a:@a,ok:"+d+",c:@c})";if("string"==typeof c)switch(b=[],s(c,3,b)[1]){case 0:case 1:d=r(b,"$",d,"@a");break;default:d="(@w="+d+"),("+r(b,"$","@w","@a")+")"}else d="@rs($,"+d+",@a)";return this.select(d,{rs:c,i:a,a:k,c:e})};f.prototype.intersect=function(a,d,b){var c;c=d?"string"==typeof d?w(d):"@c":"null";return this.where("@t.contains($,"+c+",@a)",{t:q(a),a:b,c:d})};f.prototype.join=
function(a,d,b,c,e,k){a=q(a);var n;n="string"==typeof d?"("+h(d,"$","$$","@a")+")":"@oks($,$$,@a)";var m;m="string"==typeof b?"("+h(b,"$","$$","@a")+")":"@iks($,$$,@a)";var l;l=e?"string"==typeof e?h(e,"@ok",m):"@c(@ok,"+m+")":"@ok=="+m;l=w(l);var g;g="string"==typeof c?"("+h(c,"@ov","$","@a")+")":"@rs(@ov,$,@a)";var L=this;return new f(function(e,f){var m;if("string"==typeof e){m=[];var h=s(e,3,m),q=[],p;switch(h[0]){case 0:case 1:p=g;break;default:q.push("(@RS="+g+")"),p="@RS"}switch(h[1]){case 0:case 1:h=
"(@c++)";break;default:q.push("(@cc=@c++)"),h="@cc"}q.push("("+r(m,p,h,"@a0")+")");m=q.join(",")}else m="@p("+g+",@c++,@a0)";this.broken=L.each("(@ok="+n+"),(@ov=$),@i.where("+l+",@).each("+w(m)+",@)",{i:a,oks:d,iks:b,rs:c,p:e,a:k,a0:f,c:0}).broken;return this})};f.prototype.last=function(a,d){if(a)"string"==typeof a?(b={a:d},this.each("("+h(a,"$","$$","@a")+")?@r=$:0",b)):(b={a:d,p:a},this.each("@p($,$$,@a)?@r=$:0",b));else{var b={};this.each("@r=$",b)}return b.r};f.prototype.lastOrDefault=function(a,
d,b){if(1>=arguments.length){var c=this.last();return void 0===c?a:c}c=this.last(a,b);return void 0===c?d:c};f.prototype.max=function(a,d){if(!a)return this.aggregate(null,"#0>#1?#0:#1");var b;b="string"==typeof a?"("+h(a,"$","$$","@a")+")":"@s($,$$,@a)";var c={f:!0,s:a,a:d};this.each("@f?((@f=false),(@r=$),(@m="+b+"),0):((@v="+b+"),(@v>@m?((@m=@v),(@r=$)):0),0)",c);return c.r};f.prototype.min=function(a,d){if(!a)return this.aggregate(null,"#0<#1?#0:#1");var b;b="string"==typeof a?"("+h(a,"$","$$",
"@a")+")":"@s($,$$,@a)";var c={f:!0,s:a,a:d};this.each("@f?((@f=false),(@r=$),(@m="+b+"),0):((@v="+b+"),(@v<@m?((@m=@v),(@r=$)):0),0)",c);return c.r};f.prototype.orderBy=function(a,d,b){var c=new B(this);c._addContext(a||"$",d,!1,b);return c};f.prototype.orderByDesc=function(a,d,b){var c=new B(this);c._addContext(a||"$",d,!0,b);return c};f.prototype.reverse=function(){var a=this;return new f(function(d,b){var c=[];a.each("@push($$),@push($),0",c);if("string"==typeof d){var e=[],k=s(d,3,e),n,f,l;switch(k[0]){case 0:case 1:n=
"";f="l[(i-1)*2+1]";break;default:n="var v=l[(i-1)*2+1];",f="v"}switch(k[1]){case 0:case 1:k="";l="l[(i-1)*2]";break;default:k="var k=l[(i-1)*2];",l="k"}this.broken=(new Function("l","a","for(var i=l.length/2;i>0;--i){"+k+n+"if(("+r(e,f,l,"a")+")===false){return true;}}return false;"))(c,b)}else{this.broken=!1;for(e=c.length/2;0<e;--e)if(!1===d(c[2*(e-1)+1],c[2*(e-1)],b)){this.broken=!0;break}}return this})};f.prototype.select=function(a,d){var b=this,c;"string"==typeof a?(c=g.get("($_$$_a0)",a),
c||(c="("+h(a,"$","$$","@a0")+")",g.set("($_$$_a0)",a,c))):c="@s($,$$,@a0)";return new f(function(e,k){if("string"==typeof e){var n=[],f=s(e,3,n),l=[],g;switch(f[0]){case 0:g="";break;case 1:g=c;break;default:l.push("(@v="+c+")"),g="@v"}switch(f[1]){case 0:f="";break;case 1:f="(@i++)";break;default:l.push("(@j=@i++)"),f="@j"}l.push(r(n,g,f,"@a"));this.broken=b.each(l.join(","),{s:a,a0:d,a:k,i:0}).broken}else this.broken=b.each("@p("+c+",@i++,@a)",{s:a,a0:d,a:k,i:0,p:e}).broken;return this})};f.prototype.selectMany=
function(a,d){var b;b="string"==typeof a?h(a,"$","$$","@a"):"@s($,$$,@a)";var c=this;return new f(function(e,k){var f;if("string"==typeof e)switch(f=[],s(e,3,f)[1]){case 0:case 1:f=r(f,"$","(@i++)","@a0");break;default:f="(@j=@i++),("+r(f,"$","@j","@a0")+")"}else f="@p($,@i++,@a0)";this.broken=c.each("from("+b+").each("+w(f)+",@)",{s:a,a:d,a0:k,i:0,p:e});return this})};f.prototype.selectPair=function(a,d,b){var c=this,e,k;"string"==typeof a?(e=g.get("($_$$_a0)",a),e||(e="("+h(a,"$","$$","@a0")+")",
g.set("($_$$_a0)",a,e))):e="@vs($,$$,@a0)";"string"==typeof d?(k=g.get("($_$$_a0)",d),k||(k="("+h(d,"$","$$","@a0")+")",g.set("($_$$_a0)",d,k))):k="@ks($,$$,@a0)";return new f(function(f,m){var l;if("string"==typeof f){l=[];var g=s(f,3,l),h,u=[];switch(g[0]){case 0:case 1:h=e;break;default:u.push("(@VS="+e+")"),h="@VS"}switch(g[1]){case 0:case 1:g=k;break;default:u.push("(@KS="+k+")"),g="@KS"}u.push(r(l,h,g,"@a"));l=u.join(",")}else l="@p("+e+","+k+",@a)";this.broken=c.each(l,{a0:b,a:m,p:f,vs:a,ks:d}).broken;
return this})};f.prototype.sequenceEqual=function(a,d,b){var c;c=d?"string"==typeof d?h(d,"#0","#1","@a"):"@c(#0,#1,@a)":"#0==#1";return this.zip(a,c,{a:b,c:d}).all("$==true")};f.prototype.single=function(a,d){var b=!a?this.take(2):this.where(a).take(2);if(1==b.count())return b.first()};f.prototype.singleOrDefault=function(a,d,b){var c;1>=arguments.length?(c=this.take(2),d=a):c=this.where(a).take(2);var e=c.count();if(0==e)return d;if(1==e)return c.first();throw Error("The sequence has more than one element satisfying the condition.");
};f.prototype.skip=function(a){var d=this;return new f(function(b,c){var e;"string"==typeof b?(e=g.get("($_$$_a)",b),e||(e="("+h(b,"$","$$","@a")+")",g.set("($_$$_a)",b,e))):e="@p($,$$,@a)";this.broken=d.each("@c==0?"+e+":--@c",{p:b,a:c,c:a}).broken;return this})};f.prototype.skipWhile=function(a,d){var b;"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@pr($,$$,@a)";var c=this;return new f(function(e,k){var f;"string"==typeof e?(f=g.get("($_$$_a0)",
e),f||(f="("+h(e,"$","$$","@a0")+")",g.set("($_$$_a0)",e,f))):f="@p($,$$,@a0)";this.broken=c.each("@f||(@f=!"+b+")?"+f+":0",{pr:a,f:!1,a:d,a0:k}).broken;return this})};f.prototype.sum=function(){return this.aggregate(null,"#0+#1")};f.prototype.take=function(a){var d=this;return new f(function(b,c){var e;"string"==typeof b?(e=g.get("($_$$_a)",b),e||(e="("+h(b,"$","$$","@a")+")",g.set("($_$$_a)",b,e))):e="@p($,$$,@a)";var k={i:0,p:b,a:c,b:!1};this.broken=d.each("(@i++<"+a+")?"+e+":(@b=true,false)",
k).broken&&!k.b;return this})};f.prototype.takeWhile=function(a,d){var b;"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@pr($,$$,@a)";var c=this;return new f(function(e,k){var f;"string"==typeof e?(f=g.get("($_$$_a0)",e),f||(f="("+h(e,"$","$$","@a0")+")",g.set("($_$$_a0)",e,f))):f="@p($,$$,@a0)";var m={p:e,pr:a,a:d,a0:k,b:!1};this.broken=c.each(b+"?"+f+":(@b=true,false)",m).broken&&!m.b;return this})};f.prototype.toArray=function(){var a=[];this.each("@push($)",
a);return a};f.prototype.toDictionary=function(){var a={};this.each("@[$$]=$",a);return a};f.prototype.toJSON=function(a){function d(c){var e=typeof c;return"string"==e?w(c):"number"==e||"boolean"==e?c.toString():"function"==e?d(c()):b.contains(c)||(c instanceof p||c instanceof v)&&b.contains(c.data)?"null":q(c).toJSON(a)}a||(a=[]);var b=q(a),c="number"==typeof this.select("$$").first();a.push(this);if(c){var e=[];this.each(function(a){e.push(d(a))});c="["+e.join(", ")+"]"}else e=[],this.each(function(a,
b){e.push(w(b.toString())+": "+d(a))}),c="{"+e.join(", ")+"}";a.pop(this);return c};f.prototype.toString=function(a){return this.toArray().join(a||"")};f.prototype.toURLEncoded=function(){return K(null,this)};f.prototype.union=function(a,d,b){var c=[],e=q(c),k=this;return new f(function(f,g){var l;if("string"==typeof f)switch(l=[],s(f,3,l)[1]){case 0:case 1:l=r(l,"$","(@b.length-1)","@a0");break;default:l="(@bb=@b.length-1),("+r(l,"$","@bb","@a0")+")"}else l="@p($,@b.length-1,@a0)";l="@bi.contains($,@c,@a)?0:(@b.push($),"+
l+",0)";var h={c:d,b:c,bi:e,a0:g,a:b};if(k.each(l,h).broken)return this.broken=!0,this;q(a).each(l,h).broken&&(this.broken=!0);return this})};f.prototype.zip=function(a,d,b){var c;if("string"==typeof d){var e=[],k=s(d,5,e),g,m=[];switch(k[0]){case 0:case 1:g="@d[@i*2+1]";break;default:m.push("(@V=@d[@i*2+1])"),g="@V"}switch(k[2]){case 0:case 1:k="@d[@i*2]";break;default:m.push("(@K=@d[@i*2])"),k="@K"}m.push(r(e,g,"$",k,"$$","@a"));c="("+m.join(",")+")"}else c="@rs(@d[@i*2+1],$,@d[@i*2],$$,@a)";var l=
this;return new f(function(e,f){var k=[];l.each("@push($$),@push($),0",k);var g;if("string"==typeof e){g=[];var n=s(e,3,g),m,h=[];switch(n[0]){case 0:case 1:m=c;break;default:h.push("(@RS="+c+")"),m="@RS"}switch(n[1]){case 0:case 1:n="(@k++)";break;default:h.push("(@kk=@k++)"),n="@kk"}h.push(r(g,m,n,"@a0"));g="("+h.join(",")+")"}else g="@p("+c+",@k++,@a0)";this.broken=q(a).each("@i>="+k.length/2+"?false:@r="+g+",++@i,@r",{a:b,a0:f,k:0,i:0,d:k,p:e,rs:d}).broken;return this})};A(f,t);t.prototype.each=
function(a,d){var b=this.str;if("function"==typeof a){this.broken=!1;for(var c=0,e=b.length;c<e;++c)if(!1===a(b.charAt(c),c,d)){this.broken=!0;break}}else{c=g.get("each_s",a);if(!c){var c=[],f;switch(s(a,3,c)[0]){case 0:case 1:e="";f="s.charAt(i)";break;default:e="var v=s.charAt(i);",f="v"}c=new Function(z,"s","a","for(var i=0,c=s.length;i<c;++i){"+e+"if(("+r(c,f,"i","a")+")===false){return true;}}return false;");g.set("each_s",a,c)}this.broken=c(q,b,d)}return this};t.prototype.at=function(a){return this.str.charAt(a)};
t.prototype.count=function(a,d){return a?f.prototype.count.call(this,a,d):this.str.length};t.prototype.any=function(a,d){return a?f.prototype.any.call(this,a,d):0<this.str.length};t.prototype.first=function(a,d){var b=this.str;if(a)return f.prototype.first.call(this,a,d);if(0<b.length)return b.charAt(0)};t.prototype.last=function(a,d){var b=this.str;if(a)return this.reverse().first(a,d);var c=b.length;if(0<c)return b.charAt(c-1)};t.prototype.reverse=function(){return new x(this.str)};t.prototype.toJSON=
function(){return w(this.str)};t.prototype.zip=function(a,d,b){var c;if("string"==typeof d){var e=[],k,g=[];switch(s(d,5,e)[0]){case 0:case 1:k="@d.charAt(@i)";break;default:g.push("(@V=@d.charAt(@i))"),k="@V"}g.push("("+r(e,k,"$","@i","$$","@a")+")");c="("+g.join(",")+")"}else c="@rs(@d.charAt(@i),$,@i,$$,@a)";var m=this;return new f(function(e,f){var k=m.str,g;if("string"==typeof e){g=[];var n=s(e,3,g),h,p=[];switch(n[0]){case 0:case 1:h=c;break;default:p.push("(@RS="+c+")"),h="@RS"}switch(n[1]){case 0:case 1:n=
"(@k++)";break;default:p.push("(@kk=@k++)"),n="@kk"}p.push(r(g,h,n,"@a0"));g="("+p.join(",")+")"}else g="@p("+c+",@k++,@a0)";this.broken=q(a).each("@i>="+k.length+"?false:@r="+g+",++@i,@r",{a:b,a0:f,k:0,i:0,d:k,p:e,rs:d}).broken;return this})};A(f,p);p.prototype.each=function(a,d){var b=this.data;if("function"==typeof a){this.broken=!1;for(var c=0,e=b.length;c<e;++c)if(!1===a(b[c],c,d)){this.broken=!0;break}}else{c=g.get("each_a",a);if(!c){var c=[],f;switch(s(a,3,c)[0]){case 0:case 1:e="";f="d[i]";
break;default:e="var v=d[i];",f="v"}c=new Function(z,"d","a","for(var i=0,c=d.length;i<c;++i){"+e+"if(("+r(c,f,"i","a")+")===false){return true;}}return false;");g.set("each_a",a,c)}this.broken=c(q,b,d)}return this};p.prototype.at=function(a){return this.data[a]};p.prototype.count=function(a,d){return a?f.prototype.count.call(this,a,d):this.data.length};p.prototype.any=function(a,d){return a?f.prototype.any.call(this,a,d):0<this.data.length};p.prototype.first=function(a,d){if(a)return f.prototype.first.call(this,
a,d);var b=this.data;if(0<b.length)return b[0]};p.prototype.last=function(a,d){if(a)return this.reverse().first(a,d);var b=this.data;if(0<b.length)return b[b.length-1]};p.prototype.reverse=function(){return new y(this.data)};p.prototype.toJSON=function(a){a?a.push(this.data):a=[this.data];var d=f.prototype.toJSON.call(this,a);a.pop();return d};p.prototype.zip=function(a,d,b){var c;if("string"==typeof d){var e=[],k,g=[];switch(s(d,5,e)[0]){case 0:case 1:k="@d[@i]";break;default:g.push("(@V=@d[@i])"),
k="@V"}g.push("("+r(e,k,"$","@i","$$","@a")+")");c="("+g.join(",")+")"}else c="@rs(@d[@i],$,@i,$$,@a)";var m=this;return new f(function(e,f){var k=m.data,g;if("string"==typeof e){g=[];var n=s(e,3,g),h,p=[];switch(n[0]){case 0:case 1:h=c;break;default:p.push("(@RS="+c+")"),h="@RS"}switch(n[1]){case 0:case 1:n="(@k++)";break;default:p.push("(@kk=@k++)"),n="@kk"}p.push(r(g,h,n,"@a0"));g="("+p.join(",")+")"}else g="@p("+c+",@k++,@a0)";this.broken=q(a).each("@i>="+k.length+"?false:@r="+g+",++@i,@r",{a:b,
a0:f,k:0,i:0,d:k,p:e,rs:d}).broken;return this})};A(f,v);v.prototype.each=function(a,d){var b=this.data;if("function"==typeof a){this.broken=!1;for(var c in b)if(!1===a(b[c],c,d)){this.broken=!0;break}}else{c=g.get("each_o",a);if(!c){c=[];var e,f;switch(s(a,3,c)[0]){case 0:case 1:e="";f="d[k]";break;default:e="var v=d[k];",f="v"}c=new Function(z,"d","a","for(var k in d){"+e+"if(("+r(c,f,"k","a")+")===false){return true;}}return false;");g.set("each_o",a,c)}this.broken=c(q,b,d)}return this};v.prototype.at=
function(a){return this.skip(a).first()};v.prototype.reverse=function(){return new H(this.data)};v.prototype.toJSON=p.prototype.toJSON;A(t,x);x.prototype.each=function(a,d){var b=this.str;if("function"==typeof a){this.broken=!1;for(var c=b.length,e=c;0<e;--e)if(!1===a(b.charAt(e),c-e,d)){this.broken=!0;break}}else{c=g.get("each_str",a);if(!c){var c=[],f=s(a,3,c),n,m;switch(f[0]){case 0:case 1:e="";n="s.charAt(i-1)";break;default:e="var v=s.charAt(i-1);",n="v"}switch(f[1]){case 0:case 1:f="";m="(c-i)";
break;default:f="var k=c-i;",m="k"}c=new Function(z,"s","a","for(var i="+b.length+";i>0;--i){"+e+f+"if(("+r(c,n,m,"a")+")===false){return true;}}return false;");g.set("each_str",a,c)}this.broken=c(q,b,d)}return this};x.prototype.at=function(a){var d=this.str;return d.charAt(d.length-a-1)};x.prototype.first=function(a,d){var b=this.str;if(a)return f.prototype.first.call(this,a,d);if(0<b.length)return b.charAt(b.length-1)};x.prototype.last=function(a,d){var b=this.str;if(a)return this.reverse().first(a,
d);if(0<b.length)return b.charAt(0)};x.prototype.reverse=function(){return new t(this.str)};t.prototype.toJSON=function(){return w(this.toString())};x.prototype.zip=function(a,d,b){var c=this.str,e=c.length,k;if("string"==typeof d){var g=[],m,l=[];switch(s(d,5,g)[0]){case 0:case 1:m="@d.charAt("+e+"-@i-1)";break;default:l.push("(@V=@d.charAt("+e+"-@i-1))"),m="@V"}l.push("("+r(g,m,"$","@i","$$","@a")+")");k="("+l.join(",")+")"}else k="@rs(@d.charAt("+e+"-@i-1],$,@i,$$,@a)";return new f(function(f,
g){var l;if("string"==typeof f){l=[];var n=s(f,3,l),m,h=[];switch(n[0]){case 0:case 1:m=k;break;default:h.push("(@RS="+k+")"),m="@RS"}switch(n[1]){case 0:case 1:n="(@k++)";break;default:h.push("(@kk=@k++)"),n="@kk"}h.push(r(l,m,n,"@a0"));l="("+h.join(",")+")"}else l="@p("+k+",@k++,@a0)";this.broken=q(a).each("@i>="+e+"?false:@r="+l+",++@i,@r",{a:b,a0:g,k:0,i:0,d:c,p:f,rs:d}).broken;return this})};A(p,y);y.prototype.each=function(a,d){var b=this.data;if("function"==typeof a){this.broken=!1;for(var c=
b.length,e=c;0<e;--e)if(!1===a(b[e],c-e,d)){this.broken=!0;break}}else{c=g.get("each_ar",a);if(!c){var c=[],f=s(a,3,c),n,m;switch(f[0]){case 0:case 1:e="";n="d[i-1]";break;default:e="var v=d[i-1];",n="v"}switch(f[1]){case 0:case 1:f="";m="(c-i)";break;default:f="var k=c-i;",m="k"}c=new Function(z,"d","a","for(var i="+b.length+";i>0;--i){"+e+f+"if(("+r(c,n,m,"a")+")===false){return true;}}return false;");g.set("each_ar",a,c)}this.broken=c(q,b,d)}return this};y.prototype.at=function(a){var d=this.data;
return d[d.length-a-1]};y.prototype.first=function(a,d){if(a)return f.prototype.first.call(this,a,d);var b=this.data;if(0<b.length)return b[b.length-1]};y.prototype.last=function(a,d){if(a)return this.reverse().first(a,d);var b=this.data;if(0<b.length)return b[0]};y.prototype.reverse=function(){return new p(this.data)};y.prototype.zip=function(a,d,b){var c=this;return new f(function(e,f){var g=c.data,m=g.length,l;if("string"==typeof d){var h=[],p=s(d,5,h),u=[];switch(p[0]){case 0:case 1:l="@d["+m+
"-@i-1]";break;default:u.push("(@V=@d["+m+"-@i-1])"),l="@V"}u.push("("+r(h,l,"$","@i","$$","@a")+")");l="("+u.join(",")+")"}else l="@rs(@d["+m+"-@i-1],$,@i,$$,@a)";if("string"==typeof e){h=[];p=s(e,3,h);u=[];switch(p[0]){case 0:case 1:break;default:u.push("(@RS="+l+")"),l="@RS"}switch(p[1]){case 0:case 1:p="(@k++)";break;default:u.push("(@kk=@k++)"),p="@kk"}u.push(r(h,l,p,"@a0"));h="("+u.join(",")+")"}else h="@p("+l+",@k++,@a0)";this.broken=q(a).each("@i>="+m+"?false:@r="+h+",++@i,@r",{a:b,a0:f,k:0,
i:0,d:g,p:e,rs:d}).broken;return this})};A(v,H);H.prototype.each=function(a,d){var b=this.data,c=[],e;for(e in b)c.push(e),c.push(b[e]);if("string"==typeof a){b=g.get("each_or",a);if(!b){var b=[],f=s(a,3,b),h,m;switch(f[0]){case 0:case 1:e="";h="r[ii+1]";break;default:e="var v=r[ii+1];",h="v"}switch(f[1]){case 0:case 1:f="";m="r[ii]";break;default:f="var k=r[ii];",m="k"}b=new Function(z,"r","a","for(var i=r.length/2;i>0;--i){var ii=(i-1)*2;"+e+f+"if(("+r(b,h,m,"a")+")===false){return true;}}return false;");
g.set("each_or",a,b)}this.broken=b(q,c,d)}else{this.broken=!1;for(b=c.length/2;0<b;--b)if(e=2*(b-1),!1===a(c[e+1],c[e],d)){this.broken=!0;break}}return this};H.prototype.reverse=function(){return new v(this.data)};A(v,B);B.prototype._addContext=function(a,d,b,c){this.context.push({keySelector:F(a,3),comparer:F(d,3),desc:b,arg:c})};B.prototype.each=function(a,d){function b(a,b){for(var d=0,e=f.length;d<e;++d){var g=f[d],h=g.keySelector(c[2*a+1],c[2*a],g.arg),l=g.keySelector(c[2*b+1],c[2*b],g.arg),
h=g.comparer?g.comparer(h,l,g.arg):h==l?0:h<l?-1:1;if(0!=h)return(g.desc?-1:1)*h}return 0}var c=[];this.Iterable.each("@push($$),@push($),0",c);var e=q.range(c.length/2).toArray(),f=this.context;e.sort(b);if("string"==typeof a){b=g.get("each_ord",a);if(!b){var h=[],m=s(a,3,h),l,p,t;switch(m[0]){case 0:case 1:l="";p="r[n+1]";break;default:l="var v=r[n+1];",p="v"}switch(m[1]){case 0:case 1:m="";t="r[n]";break;default:m="var k=r[n];",t="k"}b=new Function(z,"l","r","a","for(var i=0;i<"+e.length+";++i){var n=l[i]*2;"+
l+m+"if(("+r(h,p,t,"a")+")===false)return true;}return false;");g.set("each_ord",a,b)}this.broken=b(q,e,c,d)}else{this.broken=!1;h=0;for(l=e.length;h<l;++h)if(p=2*e[h],!1===a(c[p+1],c[p],d)){this.broken=!0;break}}return this};B.prototype.thenBy=function(a,d,b){this._addContext(a,d,!1,b);return this};B.prototype.thenByDesc=function(a,d,b){this._addContext(a,d,!0,b);return this};q.range=function(a,d,b){switch(arguments.length){case 1:d=a;a=0;b=1;break;case 2:b=d>a?1:-1}return new f(function(c,e){if("string"==
typeof c){var f=0<b?"each_ru":"each_rd",n=g.get(f,c);n||(n=new Function("s","e","st","a","for(var i=s;i"+(0<b?"<":">")+"e;i+=st){if(("+h(c,"i","i","a")+")===false)return true;}return false;"),g.set(f,c,n));this.broken=n(a,d,b,e)}else if(this.broken=!1,0<b)for(f=a;f<d;f+=b){if(!1===c(f,f,e)){this.broken=!0;break}}else for(f=a;f>d;f+=b)if(!1===c(f,f,e)){this.broken=!0;break}return this})};q.repeat=function(a,d){return new f(function(b,c){if("string"==typeof b){var e=g.get("each_rpt",b);e||(e=new Function("c",
"e","a","for(var i=0;i<c;++i){if(("+h(b,"e","i","a")+")===false)return true;}return false;"),g.set("each_rpt",b,e));this.broken=e(d,a,c)}else{this.broken=!1;for(e=0;e<d;++e)if(!1===b(a,e,c)){this.broken=!0;break}}return this})};q.setAlias=function(a){z=a};q.Lambda={replace:h,parse:F,getHint:s,join:r};module.exports=q})();
