(function(){function D(a,c,b){if(a.length==c)return b;a=a.substr(c);return/^[0-9]+$/.exec(a)?b+"["+a+"]":b+"."+a}function s(a,c,b){var d,e=K.exec(a);e?(d=[e[1]],a=e[2],c=Array(1)):(e=L.exec(a))?(d=e[1].split(/\s*,\s*/),a=e[2],c=Array(d.length)):c=Array(c);for(var e=0,l=c.length;e<l;++e)c[e]=0;var l=0,p="";if(d)for(;e=G.exec(a);)for(var f=e[0],k=0,m=d.length;k<m;++k){if(f==d[k]){++c[k];b&&(b.push(a.substring(l,e.index)),b.push(k),l=e.index+f.length);break}}else for(d="";e=G.exec(a);){f=e[0];m=f.charAt(0);
k=null;if("$"==m)if(m=f.length,2<=m&&"$"==f[1])++c[1],b&&(k=1,d=D(f,2,""));else{if(1==m||!(f in global))++c[0],b&&(k=0,d=D(f,1,""))}else"@"==m?(m=c.length-1,++c[m],b&&(k=m,d=D(f,1,""))):"#"==m&&(m=parseInt(f.substr(1)),++c[m],b&&(k=m,d=""));b&&null!==k&&(b.push(p+a.substring(l,e.index)),b.push(k),l=e.index+f.length,p=d,d="")}b&&b.push(p+a.substring(l,a.length));return c}function h(a,c,b){var d,e=K.exec(a);if(e)d=[e[1]],a=e[2];else if(e=L.exec(a))d=e[1].split(/\s*,\s*/),a=e[2];var l=arguments,p=0<
l.length?l[l.length-1]:"";return d?a.replace(G,function(a){for(var b=0,c=d.length;b<c;++b)if(a==d[b])return l[b+1];return a}):a.replace(G,function(a){var d=a.charAt(0);if("$"==d){d=a.length;if(2<=d&&"$"==a[1])return D(a,2,b);if(1==d||!(a in global))return D(a,1,c)}else{if("@"==d)return D(a,1,p);if("#"==d)return l[parseInt(a.substr(1))+1]}return a})}function r(a,c,b){for(var d=1,e=a.length;d<e;d+=2){var l=a[d];"number"==typeof l&&(a[d]=arguments[l+1])}return a.join("")}function H(a,c){if(!a)return null;
if("function"==typeof a)return a;var b,d=/^\s*(\w+)\s*=>(.+)$/.exec(a);if(d)b=[d[1]],a=d[2];else if(d=/^\s*\(\s*([\w\s,]*)\s*\)\s*=>(.+)$/.exec(a))b=d[1].split(/\s*,\s*/),a=d[2];if(!b){b=[];for(d=0;d<c;++d)b.push("$"+d);d=[a].concat(b);a=h.apply(null,d)}b.push("return "+a+";");return Function.apply(global,b)}function x(a){var c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",
'"':'\\"',"\\":"\\\\"};return c.test(a)?'"'+a.replace(c,function(a){var c=b[a];return c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function z(a,c){var b=function(){};b.prototype=a.prototype;c.prototype=new b}function M(a,c){var b=a?a+"=":"";if("boolean"==typeof c)return b+(c?"1":"0");if("string"==typeof c)return b+encodeURIComponent(c);if("number"==typeof c)return b+c.toString();if("object"==typeof c){var d=[];n(c).each(function(b,c){c=encodeURIComponent(c);d.push(M(a?
a+"["+c+"]":c,b))});return d.join("&")}return""}function E(a,c){this.$o=n(this.o=[]);this.c=a;this.a=c}function I(){}function f(a){this.each=a}function q(a){this.data=a}function y(a){this.data=a}function A(a){this.data=a}function u(a){this.data=a}function B(a){this.data=a}function v(a){this.data=a}function J(a){this.data=a}function C(a){this.Iterable=a;this.context=[]}function n(a){return a?a instanceof f?a:a.$each?new f(function(c,b){this.broken=!1===a.$each(c,b);return this}):"string"==typeof a?
new y(a):a instanceof Array?new u(a):new v(a):new f(function(){return this})}var F="from",N=[0," ","\n","\t"],K=/^\s*(\w+)\s*=>(.+)$/,L=/^\s*\(\s*([\w\s,]*)\s*\)\s*=>(.+)$/,G=/"(?:[^"]|\\")*"|'(?:[^']|\\')*'|[\$@\w_#]+/g;E.prototype._getPrimitiveList=function(a,c){var b=this[a];b||(this[a]=b={});c=c.toString();var d=b[c];d||(b[c]=d=[],this.o.push({k:c,l:d}));return d};E.prototype._getList=function(a){var c=this.c,b;if(c)b="string"==typeof c?h(c,"$k","@k","@a"):"@c($k,@k,@a)";else{switch(typeof a){case "string":return this._getPrimitiveList("s",
a);case "number":return this._getPrimitiveList("n",a);case "boolean":return this._getPrimitiveList("b",a)}b="$k==@k"}if(c=this.$o.first(b,{k:a,c:c,a:this.a}))return c.l;c=[];this.o.push({k:a,l:c});return c};E.prototype.add=function(a,c){this._getList(a).push(c)};E.prototype.$each=function(a,c){this.broken=!this.$o.selectPair("from($l)","$k").each(a,c).broken;return this};I.prototype.getBucket=function(a){var c=this.cache;if(!c){this.cache=c={};var b=this;setTimeout(function(){b.cache=null},0)}var d=
c[a];d||(c[a]=d={});return d};I.prototype.get=function(a,c){return this.getBucket(a)[c]};I.prototype.set=function(a,c,b){this.getBucket(a)[c]=b};var g=new I;f.prototype.broken=!1;f.prototype.where=function(a,c){var b;"string"==typeof a?(b=g.get("($_$$_a0)",a),b||(b="("+h(a,"$","$$","@a0")+")",g.set("($_$$_a0)",a,b))):b="@pr($,$$,@a0)";var d=this;return new f(function(e,l){var p;"string"==typeof e?(p=g.get("($_$$_a)",e),p||(p="("+h(e,"$","$$","@a")+")",g.set("($_$$_a)",e,p))):p="@p($,$$,@a)";this.broken=
d.each(b+"?"+p+":0",{p:e,pr:a,a0:c,a:l}).broken;return this})};f.prototype.aggregate=function(a,c,b){var d;"string"==typeof c?(d=g.get("(c_$_$$_a)",c),d||(d="("+h(c,"@c","$","$$","@a")+")",g.set("(c_$_$$_a)",c,d))):d="@p(@c,$,$$,@a)";null===a?(a={p:c,f:!0,a:b},this.each("@f?(@f=false,@c=$,0):(@c="+d+",0)",a)):(a={c:a,a:b,p:c},this.each("(@c="+d+"),0",a));return a.c};f.prototype.all=function(a,c){var b;"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):
b="@p($,$$,@a)";return!this.each("!"+b+"?false:0",{a:c,p:a}).broken};f.prototype.any=function(a,c){var b;a?"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@p($,$$,@a)":b="true";return this.each(b+"?false:0",{a:c,p:a}).broken};f.prototype.at=function(a){return this.skip(a).first()};f.prototype.atOrDefault=function(a,c){var b=this.at(a);return void 0===b?c:b};f.prototype.average=function(){var a={f:!0};this.each("@f?(@f=false,@s=$,@c=1,0):(@s+=$,++@c)",
a);return a.s/a.c};f.prototype.concat=function(a){var c=this;return new f(function(b,d){this.broken=!1;if(c.each(b,d).broken||a.each(b,d).broken)return this.broken=!0,this})};f.prototype.contains=function(a,c,b){var d;c?"string"==typeof c?(d=g.get("(v_$_a)",c),d||(d="("+h(c,"@v","$","@a")+")",g.set("(v_$_a)",c,d))):d="@c(@v,$,@a)":d="$==@v";a={v:a,a:b,c:c,r:!1};this.each(d+"?((@r=true),false):0",a);return a.r};f.prototype.count=function(a,c){var b;a?"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b=
"("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@p($,$$,@a)":b="true";var d={a:c,p:a,c:0};this.each(b+"?++@c:0",d);return d.c};f.prototype.defaultIfEmpty=function(a){var c=this;return new f(function(b,d){c.each("false").broken?this.broken=c.each(b,d).broken:("string"==typeof b&&(b=H(b,3)),this.broken=!1===b(a,0,d));return this})};f.prototype.distinct=function(a,c){var b=a?",@c,@a":"",d=[],e=n(d),l=this;return new f(function(c,f){var k;"string"==typeof c?(k=g.get("($_$$_a0)",c),k||(k="("+h(c,
"$","$$","@a0")+")",g.set("($_$$_a0)",c,k))):k="@p($,$$,@a0)";this.broken=l.each("!@ll.contains($"+b+")?(@l.push($),"+k+"):0",{c:a,ll:e,l:d,p:c,a0:f}).broken;return this})};f.prototype.except=function(a,c,b){var d;d=c?",@c,@a0":"";var e=this;return new f(function(l,f){this.broken="string"==typeof l?e.each("@s.contains($"+d+")?0:("+h(l,"$","$$","@a")+")",{c:c,a0:b,s:n(a),a:f}).broken:e.each("@s.contains($"+d+")?0:@p($,$$,@a)",{c:c,a0:b,p:l,s:n(a),a:f}).broken;return this})};f.prototype.first=function(a,
c){if(a)"string"==typeof a?(b={a:c},this.each("("+h(a,"$","$$","@a")+")?(@r=$,false):0",b)):(b={a:c,p:a},this.each("@p($,$$,@a)?(@r=$,false):0",b));else{var b={};this.each("(@r=$),false",b)}return b.r};f.prototype.firstOrDefault=function(a,c,b){if(1>=arguments.length){var d=this.first();return void 0===d?a:d}d=this.first(a,b);return void 0===d?c:d};f.prototype.groupBy=function(a,c,b){var d,e,l;a&&(d=a.value,e=a.key,l=a.result);d=d||"$";e=e||"$$";return l?(a="string"==typeof l?h(l,"$","$$","@a"):"@rs($,$$,@a)",
this._getGroupIterable(d,e,c,b).selectPair(a,"$$",{rs:l,a:b})):this._getGroupIterable(d,e,c,b)};f.prototype._getGroupIterable=function(a,c,b,d){b=new E(b,d);var e=n(b),l;l="string"==typeof c?"("+h(c,"$","$$","@a")+")":"@ks($,$$,@a)";var f;f="string"==typeof a?"("+h(a,"$","$$","@a")+")":"@vs($,$$,@a)";this.each("(@k="+l+"),(@v="+f+"),@g.add(@k,@v),0",{ks:c,vs:a,g:b,a:d});return e};f.prototype.groupJoin=function(a,c,b,d,e,l){a=n(a);c="string"==typeof c?"("+h(c,"$","$$","@a")+")":"@oks($,$$,@a)";b="string"==
typeof b?"("+h(b,"$","$$","@a")+")":"@iks($,$$,@a)";b=e?"string"==typeof e?h(e,"@ok",b):"@c(@ok,"+b+")":"@ok=="+b;b=x(b);c="@i.where("+b+",{a:@a,ok:"+c+",c:@c})";if("string"==typeof d)switch(b=[],s(d,3,b)[1]){case 0:case 1:c=r(b,"$",c,"@a");break;default:c="(@w="+c+"),("+r(b,"$","@w","@a")+")"}else c="@rs($,"+c+",@a)";return this.select(c,{rs:d,i:a,a:l,c:e})};f.prototype.intersect=function(a,c,b){var d;d=c?"string"==typeof c?x(c):"@c":"null";return this.where("@t.contains($,"+d+",@a)",{t:n(a),a:b,
c:c})};f.prototype.join=function(a,c,b,d,e,l){a=n(a);var p;p="string"==typeof c?"("+h(c,"$","$$","@a")+")":"@oks($,$$,@a)";var g;g="string"==typeof b?"("+h(b,"$","$$","@a")+")":"@iks($,$$,@a)";var k;k=e?"string"==typeof e?h(e,"@ok",g):"@c(@ok,"+g+")":"@ok=="+g;k=x(k);var m;m="string"==typeof d?"("+h(d,"@ov","$","@a")+")":"@rs(@ov,$,@a)";var t=this;return new f(function(e,f){var g;if("string"==typeof e){g=[];var h=s(e,3,g),w=[],n;switch(h[0]){case 0:case 1:n=m;break;default:w.push("(@RS="+m+")"),n=
"@RS"}switch(h[1]){case 0:case 1:h="(@c++)";break;default:w.push("(@cc=@c++)"),h="@cc"}w.push("("+r(g,n,h,"@a0")+")");g=w.join(",")}else g="@p("+m+",@c++,@a0)";this.broken=t.each("(@ok="+p+"),(@ov=$),@i.where("+k+",@).each("+x(g)+",@)",{i:a,oks:c,iks:b,rs:d,p:e,a:l,a0:f,c:0}).broken;return this})};f.prototype.last=function(a,c){if(a)"string"==typeof a?(b={a:c},this.each("("+h(a,"$","$$","@a")+")?@r=$:0",b)):(b={a:c,p:a},this.each("@p($,$$,@a)?@r=$:0",b));else{var b={};this.each("@r=$",b)}return b.r};
f.prototype.lastOrDefault=function(a,c,b){if(1>=arguments.length){var d=this.last();return void 0===d?a:d}d=this.last(a,b);return void 0===d?c:d};f.prototype.max=function(a,c){if(!a)return this.aggregate(null,"#0>#1?#0:#1");var b;b="string"==typeof a?"("+h(a,"$","$$","@a")+")":"@s($,$$,@a)";var d={f:!0,s:a,a:c};this.each("@f?((@f=false),(@r=$),(@m="+b+"),0):((@v="+b+"),(@v>@m?((@m=@v),(@r=$)):0),0)",d);return d.r};f.prototype.min=function(a,c){if(!a)return this.aggregate(null,"#0<#1?#0:#1");var b;
b="string"==typeof a?"("+h(a,"$","$$","@a")+")":"@s($,$$,@a)";var d={f:!0,s:a,a:c};this.each("@f?((@f=false),(@r=$),(@m="+b+"),0):((@v="+b+"),(@v<@m?((@m=@v),(@r=$)):0),0)",d);return d.r};f.prototype.orderBy=function(a,c,b){var d=new C(this);d._addContext(a||"$",c,!1,b);return d};f.prototype.orderByDesc=function(a,c,b){var d=new C(this);d._addContext(a||"$",c,!0,b);return d};f.prototype.reverse=function(){var a=this;return new f(function(c,b){var d=[];a.each("@push($$),@push($),0",d);if("string"==
typeof c){var e=[],l=s(c,3,e),f,g,k;switch(l[0]){case 0:case 1:f="";g="l[(i-1)*2+1]";break;default:f="var v=l[(i-1)*2+1];",g="v"}switch(l[1]){case 0:case 1:l="";k="l[(i-1)*2]";break;default:l="var k=l[(i-1)*2];",k="k"}this.broken=(new Function("l","a","for(var i=l.length/2;i>0;--i){"+l+f+"if(("+r(e,g,k,"a")+")===false){return true;}}return false;"))(d,b)}else{this.broken=!1;for(e=d.length/2;0<e;--e)if(!1===c(d[2*(e-1)+1],d[2*(e-1)],b)){this.broken=!0;break}}return this})};f.prototype.select=function(a,
c){var b=this,d;"string"==typeof a?(d=g.get("($_$$_a0)",a),d||(d="("+h(a,"$","$$","@a0")+")",g.set("($_$$_a0)",a,d))):d="@s($,$$,@a0)";return new f(function(e,l){if("string"==typeof e){var f=[],g=s(e,3,f),k=[],m;switch(g[0]){case 0:m="";break;case 1:m=d;break;default:k.push("(@v="+d+")"),m="@v"}switch(g[1]){case 0:g="";break;case 1:g="(@i++)";break;default:k.push("(@j=@i++)"),g="@j"}k.push(r(f,m,g,"@a"));this.broken=b.each(k.join(","),{s:a,a0:c,a:l,i:0}).broken}else this.broken=b.each("@p("+d+",@i++,@a)",
{s:a,a0:c,a:l,i:0,p:e}).broken;return this})};f.prototype.selectMany=function(a,c){var b;b="string"==typeof a?h(a,"$","$$","@a"):"@s($,$$,@a)";var d=this;return new f(function(e,l){var f;if("string"==typeof e)switch(f=[],s(e,3,f)[1]){case 0:case 1:f=r(f,"$","(@i++)","@a0");break;default:f="(@j=@i++),("+r(f,"$","@j","@a0")+")"}else f="@p($,@i++,@a0)";this.broken=d.each("from("+b+").each("+x(f)+",@)",{s:a,a:c,a0:l,i:0,p:e});return this})};f.prototype.selectPair=function(a,c,b){var d=this,e,l;"string"==
typeof a?(e=g.get("($_$$_a0)",a),e||(e="("+h(a,"$","$$","@a0")+")",g.set("($_$$_a0)",a,e))):e="@vs($,$$,@a0)";"string"==typeof c?(l=g.get("($_$$_a0)",c),l||(l="("+h(c,"$","$$","@a0")+")",g.set("($_$$_a0)",c,l))):l="@ks($,$$,@a0)";return new f(function(f,g){var k;if("string"==typeof f){k=[];var m=s(f,3,k),h,n=[];switch(m[0]){case 0:case 1:h=e;break;default:n.push("(@VS="+e+")"),h="@VS"}switch(m[1]){case 0:case 1:m=l;break;default:n.push("(@KS="+l+")"),m="@KS"}n.push(r(k,h,m,"@a"));k=n.join(",")}else k=
"@p("+e+","+l+",@a)";this.broken=d.each(k,{a0:b,a:g,p:f,vs:a,ks:c}).broken;return this})};f.prototype.sequenceEqual=function(a,c,b){var d;d=c?"string"==typeof c?h(c,"#0","#1","@a"):"@c(#0,#1,@a)":"#0==#1";return this.zip(a,d,{a:b,c:c}).all("$==true")};f.prototype.single=function(a,c){var b=!a?this.take(2):this.where(a).take(2);if(1==b.count())return b.first()};f.prototype.singleOrDefault=function(a,c,b){var d;1>=arguments.length?(d=this.take(2),c=a):d=this.where(a).take(2);var e=d.count();if(0==e)return c;
if(1==e)return d.first();throw Error("The sequence has more than one element satisfying the condition.");};f.prototype.skip=function(a){if(0>=a)return this;var c=this;return new f(function(b,d){var e;"string"==typeof b?(e=g.get("($_$$_a)",b),e||(e="("+h(b,"$","$$","@a")+")",g.set("($_$$_a)",b,e))):e="@p($,$$,@a)";this.broken=c.each("@c==0?"+e+":--@c",{p:b,a:d,c:a}).broken;return this})};f.prototype.skipWhile=function(a,c){var b;"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+
")",g.set("($_$$_a)",a,b))):b="@pr($,$$,@a)";var d=this;return new f(function(e,f){var p;"string"==typeof e?(p=g.get("($_$$_a0)",e),p||(p="("+h(e,"$","$$","@a0")+")",g.set("($_$$_a0)",e,p))):p="@p($,$$,@a0)";this.broken=d.each("@f||(@f=!"+b+")?"+p+":0",{pr:a,f:!1,a:c,a0:f}).broken;return this})};f.prototype.sum=function(){return this.aggregate(null,"#0+#1")};f.prototype.take=function(a){if(0==a)return n();if(0>a)return this.reverse().take(-a).reverse();var c=this;return new f(function(b,d){var e;
"string"==typeof b?(e=g.get("($_$$_a)",b),e||(e="("+h(b,"$","$$","@a")+")",g.set("($_$$_a)",b,e))):e="@p($,$$,@a)";var f={i:0,p:b,a:d,b:!1};this.broken=c.each("(@i++<"+a+")?"+e+":(@b=true,false)",f).broken&&!f.b;return this})};f.prototype.takeWhile=function(a,c){var b;"string"==typeof a?(b=g.get("($_$$_a)",a),b||(b="("+h(a,"$","$$","@a")+")",g.set("($_$$_a)",a,b))):b="@pr($,$$,@a)";var d=this;return new f(function(e,f){var p;"string"==typeof e?(p=g.get("($_$$_a0)",e),p||(p="("+h(e,"$","$$","@a0")+
")",g.set("($_$$_a0)",e,p))):p="@p($,$$,@a0)";var n={p:e,pr:a,a:c,a0:f,b:!1};this.broken=d.each(b+"?"+p+":(@b=true,false)",n).broken&&!n.b;return this})};f.prototype.toArray=function(){var a=[];this.each("@push($)",a);return a};f.prototype.toDictionary=function(){var a={};this.each("@[$$]=$",a);return a};f.prototype.toJSON=function(a){function c(d){var e=typeof d;return"string"==e?x(d):"number"==e||"boolean"==e?d.toString():"function"==e?c(d()):b.contains(d)||(d instanceof u||d instanceof v)&&b.contains(d.data)?
"null":n(d).toJSON(a)}a||(a=[]);var b=n(a),d="number"==typeof this.select("$$").first();a.push(this);if(d){var e=[];this.each(function(a){e.push(c(a))});d="["+e.join(", ")+"]"}else e=[],this.each(function(a,b){e.push(x(b.toString())+": "+c(a))}),d="{"+e.join(", ")+"}";a.pop(this);return d};f.prototype.toString=function(a){return this.toArray().join(a||"")};f.prototype.toURLEncoded=function(){return M(null,this)};f.prototype.trim=function(a,c,b){var d,e;if(!a||a instanceof Array||a instanceof f)d=
a||N,a=a instanceof f?"@.contains($)":"@.indexOf($)>=0";if(!c||c instanceof Array||c instanceof f)e=c||N,c=c instanceof f?"@.contains($)":"@.indexOf($)>=0";return this.skipWhile(a,d).reverse().skipWhile(c,e).reverse()};f.prototype.union=function(a,c,b){var d=[],e=n(d),l=this;return new f(function(f,g){var k;if("string"==typeof f)switch(k=[],s(f,3,k)[1]){case 0:case 1:k=r(k,"$","(@b.length-1)","@a0");break;default:k="(@bb=@b.length-1),("+r(k,"$","@bb","@a0")+")"}else k="@p($,@b.length-1,@a0)";k="@bi.contains($,@c,@a)?0:(@b.push($),"+
k+",0)";var m={c:c,b:d,bi:e,a0:g,a:b};if(l.each(k,m).broken)return this.broken=!0,this;n(a).each(k,m).broken&&(this.broken=!0);return this})};f.prototype.zip=function(a,c,b){var d;if("string"==typeof c){var e=[],l=s(c,5,e),g,h=[];switch(l[0]){case 0:case 1:g="@d[@i*2+1]";break;default:h.push("(@V=@d[@i*2+1])"),g="@V"}switch(l[2]){case 0:case 1:l="@d[@i*2]";break;default:h.push("(@K=@d[@i*2])"),l="@K"}h.push(r(e,g,"$",l,"$$","@a"));d="("+h.join(",")+")"}else d="@rs(@d[@i*2+1],$,@d[@i*2],$$,@a)";var k=
this;return new f(function(e,f){var l=[];k.each("@push($$),@push($),0",l);var g;if("string"==typeof e){g=[];var h=s(e,3,g),p,w=[];switch(h[0]){case 0:case 1:p=d;break;default:w.push("(@RS="+d+")"),p="@RS"}switch(h[1]){case 0:case 1:h="(@k++)";break;default:w.push("(@kk=@k++)"),h="@kk"}w.push(r(g,p,h,"@a0"));g="("+w.join(",")+")"}else g="@p("+d+",@k++,@a0)";this.broken=n(a).each("@i>="+l.length/2+"?false:@r="+g+",++@i,@r",{a:b,a0:f,k:0,i:0,d:l,p:e,rs:c}).broken;return this})};z(f,q);q.prototype.each=
function(a,c){var b=this.data;if("function"==typeof a){this.broken=!1;for(var d=0,b=b.length;d<b;++d)if(!1===a(this.at(d),d,c)){this.broken=!0;break}}else{var d=this._dataType,e=g.get("each_"+d,a);if(!e){var e=[],f,h;switch(s(a,3,e)[0]){case 0:case 1:f="";h=this.lambdaAt("s","i","c");break;default:f="var v="+this.lambdaAt("s","i","c")+";",h="v"}e=new Function(F,"s","a","for(var i=0,c=s.length;i<c;++i){"+f+"if(("+r(e,h,"i","a")+")===false){return true;}}return false;");g.set("each_"+d,a,e)}this.broken=
e(n,b,c)}return this};q.prototype.count=function(a,c){return a?f.prototype.count.call(this,a,c):this.data.length};q.prototype.any=function(a,c){return a?f.prototype.any.call(this,a,c):0<this.data.length};q.prototype.first=function(a,c){if(a)return f.prototype.first.call(this,a,c);if(0<this.data.length)return this.at(0)};q.prototype.last=function(a,c){if(a)return this.reverse().first(a,c);var b=this.data.length;if(0<b)return this.at(b-1)};q.prototype.zip=function(a,c,b){var d=this;return new f(function(e,
f){var g=d.data,h=g.length,k;if("string"==typeof c){var m=[],t=s(c,5,m),q=[];switch(t[0]){case 0:case 1:k=d.lambdaAt("@d","@i",h);break;default:q.push("(@V="+d.lambdaAt("@d","@i",h)+")"),k="@V"}q.push("("+r(m,k,"$","@i","$$","@a")+")");k="("+q.join(",")+")"}else k="@rs("+d.lambdaAt("@d","@i",h)+",$,@i,$$,@a)";if("string"==typeof e){m=[];t=s(e,3,m);q=[];switch(t[0]){case 0:case 1:break;default:q.push("(@RS="+k+")"),k="@RS"}switch(t[1]){case 0:case 1:t="(@k++)";break;default:q.push("(@kk=@k++)"),t=
"@kk"}q.push(r(m,k,t,"@a0"));m="("+q.join(",")+")"}else m="@p("+k+",@k++,@a0)";this.broken=n(a).each("@i>="+h+"?false:@r="+m+",++@i,@r",{a:b,a0:f,k:0,i:0,d:g,p:e,rs:c}).broken;return this})};z(q,y);y.prototype._dataType="string";y.prototype.lambdaAt=function(a,c){return a+".charAt("+c+")"};y.prototype.at=function(a){return this.data.charAt(a)};y.prototype.reverse=function(){return new A(this.data)};y.prototype.toString=function(a){return a?f.prototype.toString.call(this,a):this.data};y.prototype.toJSON=
function(){return x(this.data)};z(q,A);A.prototype._dataType="string_reversed";A.prototype.lambdaAt=function(a,c,b){return a+".charAt("+b+"-"+c+"-1)"};A.prototype.at=function(a){var c=this.data;return c.charAt(c.length-a-1)};A.prototype.reverse=function(){return new y(this.str)};A.prototype.toJSON=function(){return x(this.toString())};z(q,u);u.prototype._dataType="array";u.prototype.lambdaAt=function(a,c){return a+"["+c+"]"};u.prototype.at=function(a){return this.data[a]};u.prototype.reverse=function(){return new B(this.data)};
u.prototype.toJSON=function(a){a?a.push(this.data):a=[this.data];var c=f.prototype.toJSON.call(this,a);a.pop();return c};z(q,B);B.prototype._dataType="array_reversed";B.prototype.lambdaAt=function(a,c,b){return a+"["+b+"-"+c+"-1]"};B.prototype.at=function(a){var c=this.data;return c[c.length-a-1]};B.prototype.at=function(a){var c=this.data;return c[c.length-a-1]};B.prototype.reverse=function(){return new u(this.data)};z(f,v);v.prototype.each=function(a,c){var b=this.data;if("function"==typeof a){this.broken=
!1;for(var d in b)if(!1===a(b[d],d,c)){this.broken=!0;break}}else{d=g.get("each_o",a);if(!d){d=[];var e,f;switch(s(a,3,d)[0]){case 0:case 1:e="";f="d[k]";break;default:e="var v=d[k];",f="v"}d=new Function(F,"d","a","for(var k in d){"+e+"if(("+r(d,f,"k","a")+")===false){return true;}}return false;");g.set("each_o",a,d)}this.broken=d(n,b,c)}return this};v.prototype.at=function(a){return this.skip(a).first()};v.prototype.reverse=function(){return new J(this.data)};v.prototype.toJSON=u.prototype.toJSON;
z(v,J);J.prototype.each=function(a,c){var b=this.data,d=[],e;for(e in b)d.push(e),d.push(b[e]);if("string"==typeof a){b=g.get("each_or",a);if(!b){var b=[],f=s(a,3,b),h,q;switch(f[0]){case 0:case 1:e="";h="r[ii+1]";break;default:e="var v=r[ii+1];",h="v"}switch(f[1]){case 0:case 1:f="";q="r[ii]";break;default:f="var k=r[ii];",q="k"}b=new Function(F,"r","a","for(var i=r.length/2;i>0;--i){var ii=(i-1)*2;"+e+f+"if(("+r(b,h,q,"a")+")===false){return true;}}return false;");g.set("each_or",a,b)}this.broken=
b(n,d,c)}else{this.broken=!1;for(b=d.length/2;0<b;--b)if(e=2*(b-1),!1===a(d[e+1],d[e],c)){this.broken=!0;break}}return this};J.prototype.reverse=function(){return new v(this.data)};z(v,C);C.prototype._addContext=function(a,c,b,d){this.context.push({keySelector:H(a,3),comparer:H(c,3),desc:b,arg:d})};C.prototype.each=function(a,c){function b(a,b){for(var c=0,e=f.length;c<e;++c){var g=f[c],h=g.keySelector(d[2*a+1],d[2*a],g.arg),k=g.keySelector(d[2*b+1],d[2*b],g.arg),h=g.comparer?g.comparer(h,k,g.arg):
h==k?0:h<k?-1:1;if(0!=h)return(g.desc?-1:1)*h}return 0}var d=[];this.Iterable.each("@push($$),@push($),0",d);var e=n.range(d.length/2).toArray(),f=this.context;e.sort(b);if("string"==typeof a){b=g.get("each_ord",a);if(!b){var h=[],q=s(a,3,h),k,m,t;switch(q[0]){case 0:case 1:k="";m="r[n+1]";break;default:k="var v=r[n+1];",m="v"}switch(q[1]){case 0:case 1:q="";t="r[n]";break;default:q="var k=r[n];",t="k"}b=new Function(F,"l","r","a","for(var i=0,c=l.length;i<c;++i){var n=l[i]*2;"+k+q+"if(("+r(h,m,t,
"a")+")===false)return true;}return false;");g.set("each_ord",a,b)}this.broken=b(n,e,d,c)}else{this.broken=!1;h=0;for(k=e.length;h<k;++h)if(m=2*e[h],!1===a(d[m+1],d[m],c)){this.broken=!0;break}}return this};C.prototype.thenBy=function(a,c,b){this._addContext(a,c,!1,b);return this};C.prototype.thenByDesc=function(a,c,b){this._addContext(a,c,!0,b);return this};n.range=function(a,c,b){switch(arguments.length){case 1:c=a;a=0;b=1;break;case 2:b=c>a?1:-1}return new f(function(d,e){if("string"==typeof d){var f=
0<b?"each_ru":"each_rd",n=g.get(f,d);n||(n=new Function("s","e","st","a","for(var i=s;i"+(0<b?"<":">")+"e;i+=st){if(("+h(d,"i","i","a")+")===false)return true;}return false;"),g.set(f,d,n));this.broken=n(a,c,b,e)}else if(this.broken=!1,0<b)for(f=a;f<c;f+=b){if(!1===d(f,f,e)){this.broken=!0;break}}else for(f=a;f>c;f+=b)if(!1===d(f,f,e)){this.broken=!0;break}return this})};n.repeat=function(a,c){return new f(function(b,d){if("string"==typeof b){var e=g.get("each_rpt",b);e||(e=new Function("c","e","a",
"for(var i=0;i<c;++i){if(("+h(b,"e","i","a")+")===false)return true;}return false;"),g.set("each_rpt",b,e));this.broken=e(c,a,d)}else{this.broken=!1;for(e=0;e<c;++e)if(!1===b(a,e,d)){this.broken=!0;break}}return this})};n.setAlias=function(a){F=a};n.Lambda={replace:h,parse:H,getHint:s,join:r};module.exports=n})();
